# Generated by Django 4.2.2 on 2023-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aturan_lelang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('jenis_kebjakan', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nomor', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('nama_kebijakan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='upload/images/')),
                ('tag', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='history_lelang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hasil', models.TextField()),
                ('nama_lelang', models.TextField()),
                ('pemenang', models.TextField()),
                ('tahun', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField()),
                ('pita', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='istilah_lelang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_istilah', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('penjelasan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lelang_mancanegara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('keterangan', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tahun', models.CharField(max_length=4)),
                ('pita', models.TextField(max_length=100)),
                ('negara', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portal_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_header', models.ImageField(upload_to='upload/images/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.TextField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
