# Generated by Django 4.2.2 on 2023-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
