# Generated by Django 4.2.2 on 2023-06-10 15:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_banner_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lelang_mancanegara',
            name='negara',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
