# Generated by Django 4.2.2 on 2023-06-11 03:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_lelang_mancanegara_negara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istilah_lelang',
            name='penjelasan',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lelang_mancanegara',
            name='keterangan',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
