# Generated by Django 4.2.2 on 2023-06-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_istilah_lelang_penjelasan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('latar_belakang', models.TextField(blank=True, null=True)),
                ('visi', models.TextField(blank=True, null=True)),
                ('misi', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
