# Generated by Django 4.2.2 on 2023-06-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
