# Generated by Django 4.2.2 on 2023-07-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_profil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='nama_banner',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
