# Generated by Django 4.2.2 on 2023-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_banner_nama_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_lelang',
            name='penyelenggara',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lelang_mancanegara',
            name='nama_negara',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='hasil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='nama_lelang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='pemenang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='pita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='tahun',
            field=models.DateField(blank=True, null=True),
        ),
    ]
