# Generated by Django 4.2.2 on 2023-07-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_history_lelang_penyelenggara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_lelang',
            name='bandwith',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lelang_mancanegara',
            name='bandwith',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='sejarah_seleksi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='tugas_dir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
