# Generated by Django 4.2.2 on 2023-07-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_history_lelang_bandwith_lelang_mancanegara_bandwith_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_lelang',
            old_name='bandwith',
            new_name='bandwidth',
        ),
        migrations.RenameField(
            model_name='lelang_mancanegara',
            old_name='bandwith',
            new_name='bandwidth',
        ),
    ]
