# Generated by Django 4.2.2 on 2023-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_rename_bandwith_history_lelang_bandwidth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturan_lelang',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aturan_lelang',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
