# Generated by Django 4.2.2 on 2023-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_portal_block_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_block',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
