# Generated by Django 4.2.2 on 2023-08-07 05:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0014_portal_block_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='istilah_lelang',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AlterField(
            model_name='istilah_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Konten'),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='judul',
            field=models.CharField(max_length=100, verbose_name='Isi konten'),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='tag',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
    ]
