# Generated by Django 4.2.2 on 2023-08-07 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0015_istilah_lelang_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturan_lelang',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AddField(
            model_name='history_lelang',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AddField(
            model_name='lelang_mancanegara',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
    ]
