# Generated by Django 4.2.2 on 2023-08-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_aturan_lelang_updated_by_banner_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturan_lelang',
            name='tahun',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aturan_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AlterField(
            model_name='aturan_lelang',
            name='nama_kebijakan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AlterField(
            model_name='lelang_mancanegara',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
    ]
