# Generated by Django 4.2.2 on 2023-08-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_aturan_lelang_tahun_alter_aturan_lelang_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_lelang',
            old_name='penyelenggara',
            new_name='penyelenggaraan',
        ),
    ]
