# Generated by Django 4.2.2 on 2023-08-22 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0019_alter_portal_block_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_lelang',
            name='tahun',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
    ]
