# Generated by Django 4.2.2 on 2023-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_history_lelang_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istilah_lelang',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='istilah_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Diubah Terakhir'),
        ),
    ]
