# Generated by Django 4.2.2 on 2023-08-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_istilah_lelang_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istilah_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
