# Generated by Django 4.2.2 on 2023-08-24 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0023_alter_istilah_lelang_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aturan_lelang',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_aturan_lelang', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_banner', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_histori_lelang', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AlterField(
            model_name='istilah_lelang',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_istilah_lelang', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AlterField(
            model_name='lelang_mancanegara',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_lelang_mancanegara', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AlterField(
            model_name='portal_block',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_portal_blok', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
    ]
