# Generated by Django 4.2.2 on 2023-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_alter_aturan_lelang_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='latar_belakang',
            field=models.TextField(blank=True, null=True, verbose_name='Latar Belakang'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='misi',
            field=models.TextField(blank=True, null=True, verbose_name='Misi'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sejarah_seleksi',
            field=models.TextField(blank=True, null=True, verbose_name='Sejarah Seleksi Pita Frekuensi Radio'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tugas_dir',
            field=models.TextField(blank=True, null=True, verbose_name='Tugas Direktorat Penataan'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='visi',
            field=models.TextField(blank=True, null=True, verbose_name='Visi'),
        ),
    ]
