# Generated by Django 4.2.2 on 2023-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_alter_profil_latar_belakang_alter_profil_misi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aturan_lelang',
            name='jenis_kebjakan',
            field=models.CharField(choices=[('Undang - Undang', 'Undang - Undang'), ('Peraturan Pemerintah', 'Peraturan Pemerintah'), ('Peraturan Presiden', 'Peraturan Presiden'), ('Keputusan Presiden', 'Keputusan Presiden'), ('Instruksi Presiden', 'Instruksi Presiden'), ('Peraturan Menteri Komunikasi dan Informatika', 'Peraturan Menteri Komunikasi dan Informatika'), ('Keputusan Menteri Komunikasi dan Informatika', 'Keputusan Menteri Komunikasi dan Informatika'), ('Pedoman Menteri Komunikasi dan Informatika', 'Pedoman Menteri Komunikasi dan Informatika'), ('Lain-Lain', 'Lain-Lain')], max_length=120),
        ),
    ]
