# Generated by Django 4.2.5 on 2023-10-04 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0026_alter_aturan_lelang_jenis_kebjakan'),
    ]

    operations = [
        migrations.AddField(
            model_name='istilah_lelang',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_istilah_lelang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profil',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_profil', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
    ]
