# Generated by Django 4.2.5 on 2023-10-05 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0027_istilah_lelang_dibuat_oleh_profil_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturan_lelang',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_aturan_lelang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lelang_mancanegara',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_lelang_mancanegara', to=settings.AUTH_USER_MODEL),
        ),
    ]
