# Generated by Django 4.2.6 on 2023-11-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_history_lelang_image_alter_banner_nama_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lelang_mancanegara',
            name='image',
            field=models.ImageField(default=1, upload_to='upload/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='bandwidth',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='hasil',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='nama_lelang',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='penyelenggaraan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='pita',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_lelang',
            name='tahun',
            field=models.CharField(blank=True, null=True),
        ),
    ]
