# Generated by Django 4.2.6 on 2024-04-25 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0033_lelang_mancanegara_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice_lelang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir')),
                ('nama_notice', models.CharField(blank=True, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_notice_lelang', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_notice_lelang', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
            ],
        ),
    ]
