# Generated by Django 5.1.6 on 2025-02-10 09:13

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0034_notice_lelang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="istilah_lelang",
            name="penjelasan",
            field=prose.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="lelang_mancanegara",
            name="keterangan",
            field=prose.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="portal_block",
            name="content",
            field=prose.fields.RichTextField(verbose_name="Konten"),
        ),
    ]
