# Generated by Django 4.2.2 on 2023-07-07 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('persiapan', '0003_alter_berita_acara_persiapan_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen_seleksi',
            name='hasil_pemeriksaan',
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='nomor',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='nomor',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='nama_perusahaan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='nama_perwakilan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='nomor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='waktu_pengambilan',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='nomor',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='nomor',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_pertanyaan',
            name='nama_perusahaan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_pertanyaan',
            name='nama_perwakilan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_pertanyaan',
            name='waktu_pengambilan',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='nomor',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='nomor',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='file',
            field=models.FileField(upload_to='upload/files/persiapan/dokumen_seleksi/'),
        ),
    ]
