# Generated by Django 4.2.2 on 2023-07-07 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0004_remove_dokumen_seleksi_hasil_pemeriksaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanwizing',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='waktu_pengambilan',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='p_addendum',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='p_dokumen',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='p_pertanyaan',
            name='waktu_pengambilan',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='penyusunan_jawaban',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='simulasi',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
