# Generated by Django 4.2.2 on 2023-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0005_alter_aanwizing_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_addendum',
            name='nomor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='p_addendum',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
