# Generated by Django 4.2.2 on 2023-07-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0006_alter_p_addendum_nomor_alter_p_addendum_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara_persiapan',
            name='nomor',
            field=models.IntegerField(),
        ),
    ]
