# Generated by Django 4.2.2 on 2023-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0007_alter_berita_acara_persiapan_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulasi',
            name='nomor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simulasi',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
