# Generated by Django 4.2.2 on 2023-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0008_alter_simulasi_nomor_alter_simulasi_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanwizing',
            name='nomor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aanwizing',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
