# Generated by Django 4.2.2 on 2023-07-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0009_alter_aanwizing_nomor_alter_aanwizing_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyusunan_jawaban',
            name='nomor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penyusunan_jawaban',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
