# Generated by Django 4.2.2 on 2023-07-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0010_alter_penyusunan_jawaban_nomor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_dokumen',
            name='nomor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='p_dokumen',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
