# Generated by Django 4.2.2 on 2023-07-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0011_alter_p_dokumen_nomor_alter_p_dokumen_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanwizing',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berita_acara_persiapan',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_addendum',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_dokumen',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penyusunan_jawaban',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulasi',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
