# Generated by Django 4.2.2 on 2023-07-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0013_alter_dokumen_seleksi_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='waktu_pengambilan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_pertanyaan',
            name='waktu_pengambilan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
