# Generated by Django 4.2.2 on 2023-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0014_alter_dokumen_seleksi_waktu_pengambilan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara_persiapan',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_pertanyaan',
            name='waktu_pengambilan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
