# Generated by Django 4.2.2 on 2023-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0015_alter_berita_acara_persiapan_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='waktu_pengambilan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
