# Generated by Django 4.2.2 on 2023-07-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0016_alter_dokumen_seleksi_waktu_pengambilan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_pertanyaan',
            old_name='waktu_pengambilan',
            new_name='waktu_penyampaian',
        ),
    ]
