# Generated by Django 4.2.2 on 2023-07-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0013_alter_pengumuman_tgl_release'),
        ('persiapan', '0017_rename_waktu_pengambilan_p_pertanyaan_waktu_penyampaian'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_dokumen',
            name='auctioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.auctioner_lelang'),
        ),
    ]
