# Generated by Django 4.2.2 on 2023-07-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('persiapan', '0018_p_dokumen_auctioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_dokumen',
            name='auctioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
    ]
