# Generated by Django 4.2.2 on 2023-07-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('persiapan', '0021_aanwizing_auctioneer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
    ]
