# Generated by Django 4.2.2 on 2023-08-09 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0021_pengumuman_diubah_oleh'),
        ('persiapan', '0022_berita_acara_persiapan_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_dokumen',
            name='tahapan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang'),
        ),
    ]
