# Generated by Django 4.2.2 on 2023-08-09 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0039_customgroup_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persiapan', '0023_p_dokumen_tahapan'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_dokumen',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='p_dokumen',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='p_dokumen',
            name='bidder',
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='auctioneer',
            field=models.ManyToManyField(to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='bidder',
            field=models.ManyToManyField(to='userman.bidder'),
        ),
    ]
