# Generated by Django 4.2.2 on 2023-08-09 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm_lelang', '0021_pengumuman_diubah_oleh'),
        ('userman', '0039_customgroup_last_updated'),
        ('persiapan', '0024_p_dokumen_diubah_oleh_remove_p_dokumen_auctioneer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='tahapan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang'),
        ),
        migrations.RemoveField(
            model_name='berita_acara_persiapan',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='berita_acara_persiapan',
            name='bidder',
        ),
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='auctioneer',
            field=models.ManyToManyField(to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='berita_acara_persiapan',
            name='bidder',
            field=models.ManyToManyField(to='userman.bidder'),
        ),
    ]
