# Generated by Django 4.2.2 on 2023-08-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0021_pengumuman_diubah_oleh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userman', '0039_customgroup_last_updated'),
        ('persiapan', '0025_berita_acara_persiapan_diubah_oleh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen_seleksi',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='dokumen_seleksi',
            name='nama_perusahaan',
        ),
        migrations.RemoveField(
            model_name='dokumen_seleksi',
            name='nama_perwakilan',
        ),
        migrations.RemoveField(
            model_name='dokumen_seleksi',
            name='waktu_pengambilan',
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='berita_acara_persiapan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.CreateModel(
            name='pengambilan_dokumen_seleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_download', models.DateTimeField(auto_now_add=True)),
                ('bidder_perwakilan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan')),
                ('dokumen_seleksi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persiapan.dokumen_seleksi')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
