# Generated by Django 4.2.2 on 2023-08-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0059_bidder_user_created_bidder_user_last_updated'),
        ('persiapan', '0026_remove_dokumen_seleksi_bidder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_pertanyaan',
            name='nama_perusahaan',
        ),
        migrations.RemoveField(
            model_name='p_pertanyaan',
            name='nama_perwakilan',
        ),
        migrations.RemoveField(
            model_name='p_pertanyaan',
            name='waktu_penyampaian',
        ),
        migrations.AddField(
            model_name='p_pertanyaan',
            name='perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan'),
        ),
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='file',
            field=models.FileField(upload_to='upload/files/persiapan/dokumen_seleksi/', verbose_name='Ambil dokumen'),
        ),
        migrations.AlterField(
            model_name='p_pertanyaan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user'),
        ),
    ]
