# Generated by Django 4.2.2 on 2023-08-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0028_alter_p_dokumen_auctioneer_alter_p_dokumen_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengambilan_dokumen_seleksi',
            name='item_lelang',
        ),
    ]
