# Generated by Django 4.2.2 on 2023-08-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
        ('persiapan', '0029_remove_pengambilan_dokumen_seleksi_item_lelang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_pertanyaan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Unggah'),
        ),
        migrations.CreateModel(
            name='pengambilan_dokumen_addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_download', models.DateTimeField(auto_now_add=True)),
                ('bidder_perwakilan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan')),
                ('dokumen_addendum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persiapan.p_addendum')),
            ],
        ),
    ]
