# Generated by Django 4.2.2 on 2023-08-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persiapan', '0030_alter_p_pertanyaan_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara_persiapan',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/files/'),
        ),
        migrations.AlterField(
            model_name='p_dokumen',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/files/'),
        ),
    ]
