# Generated by Django 4.2.2 on 2023-08-23 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persiapan', '0031_alter_berita_acara_persiapan_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara_persiapan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_ba_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_dokumen_seleksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p_dokumen',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_p_dokumen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='daftar_hadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perwakilan', models.CharField(blank=True, null=True)),
                ('nama_perusahaan', models.CharField(blank=True, null=True)),
                ('tgl_kehadiran', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='diubah_oleh_daftar_hadir')),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
