# Generated by Django 4.2.2 on 2023-08-23 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persiapan', '0032_alter_berita_acara_persiapan_diubah_oleh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar_hadir',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='diubah_oleh_daftar_hadir'),
        ),
        migrations.AlterField(
            model_name='daftar_hadir',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
    ]
