# Generated by Django 4.2.2 on 2023-08-24 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0044_alter_undangan_unique_together'),
        ('persiapan', '0033_alter_daftar_hadir_diubah_oleh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar_hadir',
            name='item_lelang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang'),
        ),
    ]
