# Generated by Django 4.2.2 on 2023-08-24 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persiapan', '0034_daftar_hadir_item_lelang'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_addendum',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_paddendum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='p_addendum',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_paddendum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p_addendum',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
    ]
