# Generated by Django 4.2.2 on 2023-08-24 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persiapan', '0035_p_addendum_dibuat_oleh_p_addendum_diubah_oleh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanwizing',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_aanwizing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aanwizing',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_aanwizing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daftar_hadir',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_daftar_hadir', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dokumen_seleksi',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_dokumen_seleksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='p_dokumen',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_p_dokumen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='p_pertanyaan',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_p_pertanyaan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='p_pertanyaan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_p_pertanyaan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_penyusunan_jawaban', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penyusunan_jawaban',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_penyusunan_jawaban', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_simulasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulasi',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_simulasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aanwizing',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='daftar_hadir',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_daftar_hadir', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
        migrations.AlterField(
            model_name='dokumen_seleksi',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='p_dokumen',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='p_pertanyaan',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='p_pertanyaan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='penyusunan_jawaban',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='simulasi',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
    ]
