# Generated by Django 4.2.2 on 2023-08-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0063_alter_bidder_active'),
        ('persiapan', '0036_aanwizing_dibuat_oleh_aanwizing_diubah_oleh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar_hadir',
            name='bidder_perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan'),
        ),
    ]
