# Generated by Django 4.2.2 on 2023-08-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0049_pengumuman_tahapan'),
        ('userman', '0064_alter_bidder_perwakilan_nik_perwakilan'),
        ('persiapan', '0038_pengambilan_dokumen_addendum_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar_hadir',
            name='tahapan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang2'),
        ),
        migrations.AlterField(
            model_name='daftar_hadir',
            name='bidder_perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan', verbose_name='Perwakilan Perusahaan'),
        ),
    ]
