# Generated by Django 4.2.2 on 2023-08-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0049_pengumuman_tahapan'),
        ('persiapan', '0039_daftar_hadir_tahapan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar_hadir',
            name='bidder_perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.bidder_lelang', verbose_name='Perwakilan Perusahaan'),
        ),
    ]
