# Generated by Django 4.2.2 on 2023-08-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0064_alter_bidder_perwakilan_nik_perwakilan'),
        ('persiapan', '0040_alter_daftar_hadir_bidder_perwakilan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar_hadir',
            name='bidder_perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan', verbose_name='Perwakilan Perusahaan'),
        ),
    ]
