# Generated by Django 4.2.6 on 2024-05-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adm_lelang', '0061_alter_alamat_panitia_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userman', '0069_alter_users_nama_lengkap_alter_users_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampul2', models.CharField(blank=True, choices=[('Ada', 'Sesuai'), ('Tidak Ada', 'Tidak Sesuai'), ('na', 'N/A')], default='na', max_length=10, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_sampul2_form_verifikasi', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_sampul2_form_verifikasi', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang')),
            ],
        ),
        migrations.CreateModel(
            name='form_pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampul2', models.CharField(blank=True, choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada'), ('na', 'N/A')], default='na', max_length=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_sampul2_form_pemeriksaan', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_sampul2_form_pemeriksaan', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang')),
            ],
        ),
        migrations.CreateModel(
            name='form_evaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.FloatField()),
                ('blok', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='upload/files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_sampul2_form_evaluasi', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_sampul2_form_evaluasi', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang')),
            ],
        ),
    ]
