# Generated by Django 5.1.6 on 2025-02-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adm_lelang", "0061_alter_alamat_panitia_status_and_more"),
        ("sampul2", "0002_evaluasi_penawaran_hasil_sampul2_and_more"),
        ("userman", "0071_alter_usermenugroup_group_alter_usermenugroup_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obyek_seleksi_sampul2",
            name="bidder_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
                verbose_name="Bidder",
            ),
        ),
        migrations.AlterField(
            model_name="obyek_seleksi_sampul2",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adm_lelang.detail_itemlelang",
                verbose_name="Obyek Seleksi",
            ),
        ),
        migrations.AlterField(
            model_name="penawaran",
            name="perwakilan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_perwakilan",
            ),
        ),
    ]
