# Generated by Django 4.2.2 on 2023-06-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_summary_smra',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('max_block', models.IntegerField()),
                ('band', models.TextField()),
                ('item_id', models.IntegerField()),
                ('spectrum_cap', models.IntegerField()),
                ('eligibility_point_per_block', models.IntegerField()),
                ('reserved_price', models.FloatField()),
                ('count', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bid_bidder_smra',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('penawaran', models.FloatField()),
                ('round', models.IntegerField()),
                ('available_block', models.IntegerField()),
                ('band', models.TextField()),
                ('spectrum_cap', models.IntegerField()),
                ('eligibility_point_per_block', models.IntegerField()),
                ('block', models.IntegerField()),
                ('prev_block', models.IntegerField()),
                ('bidder_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('reserved_price', models.FloatField()),
                ('prev_price', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bidding_round_smra',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('round_state', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='adm_lelang.item_lelang')),
                ('status_round', models.CharField(choices=[('STA', 'START'), ('STO', 'STOP'), ('SUS', 'SUSPEND'), ('CLO', 'CLOSED'), ('INI', 'INIT'), ('NON', 'NONE')], default='NON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='round_schedule_smra',
            fields=[
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('durasi', models.IntegerField(default=30)),
                ('harian_mulai', models.TimeField()),
                ('harian_selesai', models.TimeField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.CreateModel(
            name='round_smra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.FloatField()),
                ('block', models.IntegerField()),
                ('prev_price', models.FloatField(null=True)),
                ('prev_block', models.IntegerField(null=True)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
