# Generated by Django 4.2.2 on 2023-06-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0001_initial'),
        ('userman', '0033_usermenu_order'),
        ('smra', '0002_alter_round_smra_item_round_smra_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='round_smra_sum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.FloatField(null=True)),
                ('activity', models.IntegerField(null=True)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
