# Generated by Django 4.2.2 on 2023-06-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra', '0003_round_smra_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_smra',
            name='min_price',
            field=models.FloatField(null=True),
        ),
    ]
