# Generated by Django 4.2.2 on 2023-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra', '0004_round_smra_min_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='eli_round',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('bidder_id', models.IntegerField()),
                ('pbpp', models.FloatField(null=True)),
                ('cbpp', models.FloatField(null=True)),
                ('pbcp', models.FloatField(null=True)),
                ('cbcp', models.FloatField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='round_smra_temp',
            name='min_price',
            field=models.FloatField(null=True),
        ),
    ]
