# Generated by Django 4.2.2 on 2023-06-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra', '0006_round_smra_sum_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_round_smra',
            name='start_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
