# Generated by Django 4.2.2 on 2023-06-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0004_alamat_panitia'),
        ('smra', '0007_bidding_round_smra_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_schedule_smra',
            name='durasi',
        ),
        migrations.RemoveField(
            model_name='round_schedule_smra',
            name='harian_mulai',
        ),
        migrations.RemoveField(
            model_name='round_schedule_smra',
            name='harian_selesai',
        ),
        migrations.AddField(
            model_name='round_schedule_smra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round_schedule_smra',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang'),
        ),
        migrations.AlterField(
            model_name='round_schedule_smra',
            name='mulai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='round_schedule_smra',
            name='selesai',
            field=models.DateTimeField(),
        ),
    ]
