# Generated by Django 4.2.2 on 2023-07-06 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('smra', '0011_alter_bidding_round_smra_status_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='undangan_smra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('judul', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('tempat', models.CharField(max_length=100)),
                ('waktu', models.DateTimeField()),
                ('agenda', models.TextField()),
                ('link_teleconference', models.TextField()),
                ('keterangan', models.TextField()),
                ('link_file', models.FileField(upload_to='upload/files/pasca_seleksi/sanggahan_jawaban/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
