# Generated by Django 4.2.2 on 2023-07-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra', '0013_undangan_smra_cca_delete_undangan_smra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undangan_smra_cca',
            name='waktu',
        ),
        migrations.AlterField(
            model_name='undangan_smra_cca',
            name='owner',
            field=models.TextField(blank=True, choices=[('SMRA', 'SMRA'), ('CCA', 'CCA'), ('BC', 'Beauty Contest'), ('PBC', 'Penilaian Beauty Contest'), ('GABUNGAN', 'Gabungan'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='undangan_smra_cca',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
