# Generated by Django 4.2.2 on 2023-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra', '0014_remove_undangan_smra_cca_waktu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undangan_smra_cca',
            name='nomor',
            field=models.CharField(),
        ),
    ]
