# Generated by Django 4.2.2 on 2023-07-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('smra', '0015_alter_undangan_smra_cca_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undangan_smra_cca',
            name='link_file',
            field=models.FileField(upload_to='upload/files/pasca_seleksi/sanggahan_jawaban/', verbose_name='Link Undangan'),
        ),
        migrations.AlterField(
            model_name='undangan_smra_cca',
            name='link_teleconference',
            field=models.TextField(verbose_name='Link Teleconference'),
        ),
        migrations.CreateModel(
            name='round_cca2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.FloatField()),
                ('block', models.IntegerField()),
                ('prev_price', models.FloatField(null=True)),
                ('prev_block', models.IntegerField(null=True)),
                ('min_price', models.FloatField(null=True)),
                ('status_round', models.CharField(choices=[('STA', 'START'), ('STO', 'STOP'), ('SUS', 'SUSPEND'), ('CLO', 'CLOSED'), ('INI', 'INIT'), ('NON', 'NONE'), ('WAI', 'WAIT')], default='NON', max_length=3)),
                ('mulai', models.DateTimeField()),
                ('selesai', models.DateTimeField()),
                ('lock', models.BooleanField(default=False)),
                ('jenis', models.CharField(choices=[('CLK', 'CLOCK'), ('SUP', 'SUPPLEMENTAL'), ('WIN', 'WINNIND')], default='CLK', max_length=3)),
                ('penawaran', models.FloatField(null=True)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
