# Generated by Django 4.2.2 on 2023-07-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('userman', '0033_usermenu_order'),
        ('smra', '0016_alter_undangan_smra_cca_link_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_cca2',
            name='item_lelang',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round_cca2',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.CreateModel(
            name='hasil_cca2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.FloatField()),
                ('block', models.IntegerField()),
                ('item_lelang', models.IntegerField(null=True)),
                ('submit', models.DateTimeField(auto_now_add=True, null=True)),
                ('penawaran', models.FloatField(null=True)),
                ('valid', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang')),
            ],
        ),
    ]
