# Generated by Django 4.2.2 on 2023-07-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('smra', '0017_round_cca2_item_lelang_alter_round_cca2_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='round_cca2_sum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.JSONField(null=True)),
                ('prev_price', models.JSONField(null=True)),
                ('activity', models.IntegerField(null=True)),
                ('corrected', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
