# Generated by Django 4.2.2 on 2023-07-18 07:36

from django.db import migrations
import smra.models


class Migration(migrations.Migration):

    dependencies = [
        ('smra', '0018_round_cca2_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_schedule_smra',
            name='hari',
            field=smra.models.DayOfTheWeekField(choices=[('1', 'Senin'), ('2', 'Selasa'), ('3', 'Rabu'), ('4', 'Kamis'), ('5', 'Jumat'), ('6', 'Sabtu'), ('7', 'Minggu')], max_length=1, null=True),
        ),
    ]
