# Generated by Django 4.2.2 on 2023-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra', '0019_round_schedule_smra_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_schedule_smra',
            name='mulai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='round_schedule_smra',
            name='selesai',
            field=models.TimeField(),
        ),
    ]
