# Generated by Django 4.2.2 on 2023-07-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('smra', '0020_alter_round_schedule_smra_mulai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='undangan_smra_cca',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='undangan_smra_cca',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
    ]
