# Generated by Django 4.2.2 on 2023-07-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0018_alter_template_berita_acara_template_code_sub'),
        ('userman', '0033_usermenu_order'),
        ('smra', '0021_undangan_smra_cca_auctioneer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='berita_acara_lelang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('owner', models.TextField(blank=True, choices=[('SMRA', 'SMRA'), ('CCA', 'CCA'), ('BC', 'Beauty Contest'), ('PBC', 'Penilaian Beauty Contest'), ('GABUNGAN', 'Gabungan'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auctioneer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang')),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
