# Generated by Django 4.2.2 on 2023-08-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0036_bidder_perwakilan_nik_perwakilan_and_more'),
        ('smra', '0022_berita_acara_lelang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undangan_smra_cca',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='undangan_smra_cca',
            name='bidder',
        ),
        migrations.AddField(
            model_name='undangan_smra_cca',
            name='auctioneer',
            field=models.ManyToManyField(to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='undangan_smra_cca',
            name='bidder',
            field=models.ManyToManyField(to='userman.bidder'),
        ),
    ]
