# Generated by Django 4.2.2 on 2023-06-21 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tahapan_lelang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahapan', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='panitia_seleksi',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='penetapan_pemenang',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='release_lelang',
            name='release_item',
        ),
        migrations.DeleteModel(
            name='sanggahan',
        ),
        migrations.AddField(
            model_name='item_lelang',
            name='tahun',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='dokumen',
            field=models.FileField(null=True, upload_to='upload/adm_lelang/'),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='tgl_release',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persyaratan_lelang',
            name='dokumen',
            field=models.FileField(null=True, upload_to='upload/adm_lelang/'),
        ),
        migrations.AlterField(
            model_name='auctioner_lelang',
            name='auctioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang', verbose_name='Auctioneer'),
        ),
        migrations.DeleteModel(
            name='panitia_seleksi',
        ),
        migrations.DeleteModel(
            name='penetapan_pemenang',
        ),
        migrations.DeleteModel(
            name='release_lelang',
        ),
    ]
