# Generated by Django 4.2.2 on 2023-06-21 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0002_tahapan_lelang_remove_panitia_seleksi_item_lelang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwal_seleksi',
            old_name='agenda',
            new_name='perubahan',
        ),
        migrations.RemoveField(
            model_name='jadwal_seleksi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jadwal_seleksi',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='jadwal_seleksi',
            name='tahap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang'),
        ),
        migrations.AddField(
            model_name='jadwal_seleksi',
            name='tanggal_akhir',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwal_seleksi',
            name='tanggal_awal',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
