# Generated by Django 4.2.2 on 2023-06-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0003_rename_agenda_jadwal_seleksi_perubahan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alamat_panitia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=100, null=True)),
                ('kodepos', models.CharField(max_length=5, null=True)),
                ('telp', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cq', models.CharField(max_length=255, null=True)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
