# Generated by Django 4.2.2 on 2023-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0004_alamat_panitia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='tgl_release',
            field=models.DateField(null=True),
        ),
    ]
