# Generated by Django 4.2.2 on 2023-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0005_alter_pengumuman_tgl_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_lelang',
            name='ip_address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
