# Generated by Django 4.2.2 on 2023-06-23 13:42

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0007_alter_bidder_lelang_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_lelang',
            name='state',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='new', name='AuctionWorkflow', states=['new', 'old'])),
        ),
    ]
