# Generated by Django 4.2.2 on 2023-06-23 13:54

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0008_item_lelang_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_lelang',
            name='state',
            field=django_xworkflows.models.StateField(max_length=20, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='rencana', name='AuctionWorkflow', states=['rencana', 'persiapan_pengumuman', 'persiapan_doksel', 'persiapan_pertanyaan'])),
        ),
    ]
