# Generated by Django 4.2.2 on 2023-06-23 14:18

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0009_alter_item_lelang_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_lelang',
            name='state',
            field=django_xworkflows.models.StateField(max_length=26, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='start', name='AuctionWorkflow', states=['start', 'rencana', 'persiapan_pengumuman', 'persiapan_doksel', 'persiapan_pertanyaan', 'persiapan_jawaban', 'persiapan_aanwizing', 'persiapan_simulasi', 'administrasi_keikutsertaan', 'administrasi_pemeriksaan', 'administrasi_verifikasi', 'administrasi_pengumuman', 'administrasi_sanggah', 'administrasi_hasil', 'smra_persiapan', 'smra_lelang', 'smra_lelang_khusus', 'smra_lelang_penetapan', 'smra_hasil_seleksi', 'bc_persiapan', 'bc_penyampaian', 'bc_evaluasi', 'bc_hasil_seleksi', 'cca_persiapan', 'cca_clock_stage', 'cca_supplement', 'cca_assignment', 'cca_hasil_seleksi', 'gabungan_persiapan', 'gabungan_hasil', 'negosiasi_persiapan', 'negosiasi_penyampaian', 'negosiasi_evaluasi', 'negosiasi_revisi', 'negosiasi_evaluasi_revisi', 'negosiasi_hasil', 'penetapan_pemilihan', 'penetapan_pengumuman', 'penetapan_sanggah', 'penetapan_pemenang', 'penetapan_pengumuman2', 'end'])),
        ),
    ]
