# Generated by Django 4.2.2 on 2023-06-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0010_alter_item_lelang_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow_state',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('transition', models.CharField(max_length=255)),
                ('from_state', models.CharField(max_length=255)),
                ('to_state', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('content_type_id', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
