# Generated by Django 4.2.2 on 2023-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0011_flow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_lelang',
            name='tayang',
            field=models.BooleanField(default=True),
        ),
    ]
