# Generated by Django 4.2.2 on 2023-07-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='tgl_release',
            field=models.DateTimeField(null=True),
        ),
    ]
