# Generated by Django 4.2.2 on 2023-07-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0013_alter_pengumuman_tgl_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='template_bertia_acara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_template', models.CharField(blank=True, max_length=255, null=True)),
                ('keterangan_template', models.CharField(blank=True, max_length=255, null=True)),
                ('template_code_menu', models.CharField(blank=True, choices=[('persiapan', 'Persiapan'), ('administrasi', 'Administrasi'), ('beauty_contest', 'Beauty Contest'), ('gabungan', 'Gabungan'), ('negosiasi', 'Negosiasi'), ('pasca_seleksi', 'Pasca Seleksi'), ('unknown', 'Unknown')], default='Unknown', max_length=255, null=True)),
                ('template_code_sub', models.CharField(blank=True, choices=[('dokumen_seleksi', 'Dokumen Seleksi'), ('pertanyaan', 'Pertanyaan'), ('aanwizing', 'Aanwizing'), ('simulasi', 'Simulasi'), ('pengambilan_addendum_doksel', 'Pengambilan Addendum Dokumen Seleksi'), ('permohonan_keikutsertaan', 'Permohonan Keikutsertaan'), ('pemeriksaan_kelengkapan', 'Pemeriksaan Kelengkapan'), ('verifikasi', 'Verifikasi'), ('hasil_evaluasi', 'Hasil Evaluasi'), ('sanggahan1', 'Sanggahan Adm'), ('beauty_contest', 'Beauty Contest'), ('gabungan', 'Gabungan'), ('sampul2', 'Sampul 2'), ('evaluasi_sampul_2', 'Evaluasi Sampul 2'), ('revisi_evaluasi_sampul_2', 'Revisi Evaluasi Sampul 2'), ('evaluasi_revisi_evaluasi_sampul_2', 'Evaluasi Revisi Evaluasi Sampul 2'), ('pemilihan_blok', 'Pemilihan Blok'), ('sanggahan2', 'Sanggahan Pasca'), ('unknown', 'Unknown')], default='Unknown', max_length=255, null=True)),
            ],
        ),
    ]
