# Generated by Django 4.2.2 on 2023-07-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0014_template_bertia_acara'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='template_bertia_acara',
            new_name='template_berita_acara',
        ),
    ]
