# Generated by Django 4.2.2 on 2023-07-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0016_template_berita_acara_item_lelang'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_berita_acara',
            name='dokumen',
            field=models.FileField(null=True, upload_to='upload/adm_lelang/'),
        ),
    ]
