# Generated by Django 4.2.2 on 2023-07-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0017_template_berita_acara_dokumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_berita_acara',
            name='template_code_sub',
            field=models.CharField(blank=True, choices=[('1_dokumen_seleksi', 'Dokumen Seleksi'), ('1_pertanyaan', 'Pertanyaan'), ('1_aanwizing', 'Aanwizing'), ('1_simulasi', 'Simulasi'), ('1_pengambilan_addendum_doksel', 'Pengambilan Addendum Dokumen Seleksi'), ('2_permohonan_keikutsertaan', 'Permohonan Keikutsertaan'), ('2_pemeriksaan_kelengkapan', 'Pemeriksaan Kelengkapan'), ('2_verifikasi', 'Verifikasi'), ('2_hasil_evaluasi', 'Hasil Evaluasi'), ('2_sanggahan1', 'Sanggahan Adm'), ('3_beauty_contest', 'Beauty Contest'), ('4_gabungan', 'Gabungan'), ('5_sampul2', 'Sampul 2'), ('5_evaluasi_sampul_2', 'Evaluasi Sampul 2'), ('5_revisi_evaluasi_sampul_2', 'Revisi Evaluasi Sampul 2'), ('5_evaluasi_revisi_evaluasi_sampul_2', 'Evaluasi Revisi Evaluasi Sampul 2'), ('6_pemilihan_blok', 'Pemilihan Blok'), ('6_sanggahan2', 'Sanggahan Pasca'), ('unknown', 'Unknown')], default='Unknown', max_length=255, null=True),
        ),
    ]
