# Generated by Django 4.2.2 on 2023-08-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0018_alter_template_berita_acara_template_code_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='owner',
            field=models.TextField(blank=True, choices=[('PEMBUKAAN', 'Pembukaan'), ('HASIL EVALUASI', 'Evaluasi'), ('HASIL SELEKSI', 'Seleksi'), ('PENETAPAN PEMENANG', 'Penetepan'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='template_berita_acara',
            name='template_code_menu',
            field=models.CharField(blank=True, choices=[('persiapan', 'Persiapan'), ('administrasi', 'Administrasi'), ('beauty_contest', 'Beauty Contest'), ('gabungan', 'Gabungan'), ('negosiasi', 'Negosiasi'), ('pasca_seleksi', 'Pasca Seleksi'), ('unknown', 'Unknown')], default='Unknown', max_length=255, null=True, verbose_name='Template Menu'),
        ),
        migrations.AlterField(
            model_name='template_berita_acara',
            name='template_code_sub',
            field=models.CharField(blank=True, choices=[('1_dokumen_seleksi', 'Dokumen Seleksi'), ('1_pertanyaan', 'Pertanyaan'), ('1_aanwizing', 'Aanwizing'), ('1_simulasi', 'Simulasi'), ('1_pengambilan_addendum_doksel', 'Pengambilan Addendum Dokumen Seleksi'), ('2_permohonan_keikutsertaan', 'Permohonan Keikutsertaan'), ('2_pemeriksaan_kelengkapan', 'Pemeriksaan Kelengkapan'), ('2_verifikasi', 'Verifikasi'), ('2_hasil_evaluasi', 'Hasil Evaluasi'), ('2_sanggahan1', 'Sanggahan Adm'), ('3_beauty_contest', 'Beauty Contest'), ('4_gabungan', 'Gabungan'), ('5_sampul2', 'Sampul 2'), ('5_evaluasi_sampul_2', 'Evaluasi Sampul 2'), ('5_revisi_evaluasi_sampul_2', 'Revisi Sampul 2'), ('5_evaluasi_revisi_evaluasi_sampul_2', 'Evaluasi Revisi Sampul 2'), ('6_pemilihan_blok', 'Pemilihan Blok'), ('6_sanggahan2', 'Sanggahan Pasca'), ('unknown', 'Unknown')], default='Unknown', max_length=255, null=True, verbose_name='Template Submenu'),
        ),
    ]
