# Generated by Django 4.2.2 on 2023-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0019_pengumuman_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahapan_lelang',
            name='code_tahapan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tahapan_lelang',
            name='tahapan_utama',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
