# Generated by Django 4.2.2 on 2023-08-09 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm_lelang', '0020_tahapan_lelang_code_tahapan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='diubah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
