# Generated by Django 4.2.2 on 2023-08-11 06:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0021_pengumuman_diubah_oleh'),
    ]

    operations = [
        migrations.CreateModel(
            name='tahapan_lelang2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tahapan')),
                ('judul', models.CharField(max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adm_lelang.tahapan_lelang2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
