# Generated by Django 4.2.2 on 2023-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0023_delete_flow_state_remove_item_lelang_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_itemlelang',
            name='reserved_price',
        ),
        migrations.AddField(
            model_name='detail_itemlelang',
            name='harga_minimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
