# Generated by Django 4.2.2 on 2023-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0024_remove_detail_itemlelang_reserved_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='band',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='rentang_frekuensi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='teknologi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item_lelang',
            name='keterangan',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item_lelang',
            name='nama_lelang',
            field=models.TextField(max_length=1000),
        ),
    ]
