# Generated by Django 4.2.2 on 2023-08-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0025_alter_detail_itemlelang_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_seleksi',
            name='tahap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang2'),
        ),
    ]
