# Generated by Django 4.2.2 on 2023-08-11 14:35

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0026_alter_jadwal_seleksi_tahap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_seleksi',
            name='tahap',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_seleksi_children', to='adm_lelang.tahapan_lelang2'),
        ),
    ]
