# Generated by Django 4.2.2 on 2023-08-13 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userman', '0047_alter_users_nama_lengkap'),
        ('adm_lelang', '0027_alter_jadwal_seleksi_tahap'),
    ]

    operations = [
        migrations.CreateModel(
            name='undangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, null=True, verbose_name='Nomor')),
                ('judul', models.CharField(blank=True, null=True, verbose_name='Perihal')),
                ('tanggal', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal')),
                ('tempat', models.TextField(blank=True, null=True, verbose_name='Tempat')),
                ('agenda', models.CharField(blank=True, null=True, verbose_name='Agenda Undangan')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Penjelasan')),
                ('link_teleconference', models.TextField(blank=True, null=True, verbose_name='Link Telekonferensi')),
                ('file', models.FileField(upload_to='upload/files/', verbose_name='Berkas Undangan')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auctioneer', models.ManyToManyField(to='userman.tim_lelang')),
                ('bidder_user', models.ManyToManyField(to='userman.bidder_user')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undangan_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undangan_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
                ('tahapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang2')),
            ],
        ),
    ]
