# Generated by Django 4.2.2 on 2023-08-15 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0059_bidder_user_created_bidder_user_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm_lelang', '0030_tahapan_lelang2_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='berita_acara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auctioneer', models.ManyToManyField(to='userman.tim_lelang')),
                ('bidder_user', models.ManyToManyField(to='userman.bidder_user')),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ba_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
                ('tahapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang2')),
            ],
        ),
    ]
