# Generated by Django 4.2.2 on 2023-08-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0059_bidder_user_created_bidder_user_last_updated'),
        ('adm_lelang', '0031_berita_acara'),
    ]

    operations = [
        migrations.CreateModel(
            name='pengambilan_undangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_download', models.DateTimeField(auto_now_add=True)),
                ('bidder_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
                ('undangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.undangan')),
            ],
        ),
        migrations.CreateModel(
            name='pengambilan_ba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_download', models.DateTimeField(auto_now_add=True)),
                ('ba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.berita_acara')),
                ('bidder_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
