# Generated by Django 4.2.2 on 2023-08-15 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm_lelang', '0032_pengambilan_undangan_pengambilan_ba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengambilan_ba',
            name='bidder_user',
        ),
        migrations.RemoveField(
            model_name='pengambilan_undangan',
            name='bidder_user',
        ),
        migrations.AddField(
            model_name='pengambilan_ba',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengambilan_undangan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
