# Generated by Django 4.2.2 on 2023-08-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0033_remove_pengambilan_ba_bidder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahapan_lelang2',
            name='orderby',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
