# Generated by Django 4.2.2 on 2023-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
        ('adm_lelang', '0034_tahapan_lelang2_orderby'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_acara',
            name='viewer',
            field=models.ManyToManyField(blank=True, to='userman.viewers'),
        ),
        migrations.AddField(
            model_name='undangan',
            name='viewer',
            field=models.ManyToManyField(blank=True, to='userman.viewers'),
        ),
        migrations.AlterField(
            model_name='berita_acara',
            name='auctioneer',
            field=models.ManyToManyField(blank=True, to='userman.tim_lelang'),
        ),
        migrations.AlterField(
            model_name='berita_acara',
            name='bidder_user',
            field=models.ManyToManyField(blank=True, to='userman.bidder_user'),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='auctioneer',
            field=models.ManyToManyField(blank=True, to='userman.tim_lelang'),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='bidder_user',
            field=models.ManyToManyField(blank=True, to='userman.bidder_user'),
        ),
    ]
