# Generated by Django 4.2.2 on 2023-08-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0035_berita_acara_viewer_undangan_viewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/files/'),
        ),
    ]
