# Generated by Django 4.2.2 on 2023-08-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0036_alter_berita_acara_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_itemlelang',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bandwidth (Mhz)'),
        ),
        migrations.AddField(
            model_name='detail_itemlelang',
            name='cakupan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Range (Dari MHz s/d MHz)'),
        ),
        migrations.AddField(
            model_name='detail_itemlelang',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='detail_itemlelang',
            name='penyelenggaraan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='band',
            field=models.CharField(max_length=100, verbose_name='Pita (Mhz)'),
        ),
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='rentang_frekuensi',
            field=models.CharField(max_length=100, verbose_name='Range (Dari MHz s/d MHz)'),
        ),
    ]
