# Generated by Django 4.2.2 on 2023-08-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0037_detail_itemlelang_bandwidth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='cakupan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cakupan'),
        ),
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Terakhir Diubah'),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='dokumen',
            field=models.FileField(null=True, upload_to='upload/adm_lelang/', verbose_name='File Pengumuman'),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='pengumuman',
            field=models.TextField(null=True, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='tgl_release',
            field=models.DateTimeField(null=True, verbose_name='Tanggal Penetapan'),
        ),
    ]
