# Generated by Django 4.2.2 on 2023-08-22 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm_lelang', '0038_pengumuman_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='penangung_jawab_seleksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, null=True)),
                ('nip', models.CharField(blank=True, null=True)),
                ('tanggung_jawab', models.CharField(blank=True, null=True)),
                ('tgl_mulai', models.DateTimeField(blank=True, null=True)),
                ('tgl_akhir', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penangung_jawab_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penangung_jawab_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
