# Generated by Django 4.2.2 on 2023-08-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0039_penangung_jawab_seleksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penangung_jawab_seleksi',
            name='nip',
            field=models.CharField(blank=True, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='penangung_jawab_seleksi',
            name='tgl_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir'),
        ),
        migrations.AlterField(
            model_name='penangung_jawab_seleksi',
            name='tgl_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai'),
        ),
    ]
