# Generated by Django 4.2.2 on 2023-08-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0040_alter_penangung_jawab_seleksi_nip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penangung_jawab_seleksi',
            name='tanggung_jawab',
            field=models.CharField(blank=True, choices=[('pengarah', 'Pengarah'), ('pembina', 'Pembina'), ('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('anggota', 'Anggota')], null=True),
        ),
    ]
