# Generated by Django 4.2.2 on 2023-08-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0041_alter_penangung_jawab_seleksi_tanggung_jawab'),
    ]

    operations = [
        migrations.AddField(
            model_name='alamat_panitia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='alamat_panitia',
            name='keterangan',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='alamat_panitia',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='alamat_panitia',
            name='provinsi',
            field=models.CharField(max_length=100, null=True, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='alamat_panitia',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alamat_panitia',
            name='kota',
            field=models.CharField(max_length=100, null=True, verbose_name='Kota/Kab'),
        ),
    ]
