# Generated by Django 4.2.2 on 2023-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0042_alamat_panitia_created_alamat_panitia_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara',
            name='file',
            field=models.FileField(blank=True, default='upload/files/kosong.pdf', upload_to='upload/files/'),
        ),
    ]
