# Generated by Django 4.2.2 on 2023-08-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0043_alter_berita_acara_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='undangan',
            unique_together={('item_lelang', 'tahapan')},
        ),
    ]
