# Generated by Django 4.2.2 on 2023-08-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0044_alter_undangan_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasar_hukum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dasar_hukum',
            name='keterangan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dasar_hukum',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AddField(
            model_name='dasar_hukum',
            name='nomor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dasar_hukum',
            name='judul',
            field=models.CharField(max_length=255, verbose_name='Judul Peraturan'),
        ),
    ]
