# Generated by Django 4.2.2 on 2023-08-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0045_dasar_hukum_created_dasar_hukum_keterangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasar_hukum',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dasar_hukum',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='upload/dasar_hukum/'),
        ),
    ]
