# Generated by Django 4.2.2 on 2023-08-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0047_alter_detail_itemlelang_rentang_frekuensi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tahapan_lelang2',
            options={'ordering': ('lft',)},
        ),
        migrations.AddField(
            model_name='undangan',
            name='waktu_akhir',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan',
            name='waktu_awal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
