# Generated by Django 4.2.2 on 2023-08-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0048_alter_tahapan_lelang2_options_undangan_waktu_akhir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='tahapan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.tahapan_lelang2'),
        ),
    ]
