# Generated by Django 4.2.2 on 2023-08-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0049_pengumuman_tahapan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='undangan',
            unique_together=set(),
        ),
    ]
