# Generated by Django 4.2.2 on 2023-08-31 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm_lelang', '0050_alter_undangan_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_acara',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ba_dibuat_oleh', to=settings.AUTH_USER_MODEL),
        ),
    ]
