# Generated by Django 4.2.2 on 2023-08-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0051_berita_acara_dibuat_oleh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='harga_minimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
