# Generated by Django 4.2.2 on 2023-09-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='tgl_release',
            field=models.DateTimeField(null=True, verbose_name='Tanggal Terbit'),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='judul',
            field=models.CharField(blank=True, null=True, verbose_name='Judul Undangan'),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='keterangan',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='nomor',
            field=models.CharField(blank=True, null=True, verbose_name='Nomor Undangan'),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal dibuat'),
        ),
    ]
