# Generated by Django 4.2.5 on 2023-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0053_alter_pengumuman_tgl_release_alter_undangan_judul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='tgl_release',
            field=models.DateTimeField(null=True, verbose_name='Tanggal Penetapan'),
        ),
    ]
