# Generated by Django 4.2.5 on 2023-10-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0054_alter_pengumuman_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persyaratan_lelang',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='persyaratan_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
        migrations.AddField(
            model_name='persyaratan_lelang',
            name='no_urut',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detail_itemlelang',
            name='band',
            field=models.CharField(max_length=100, verbose_name='Pita (MHz)'),
        ),
    ]
