# Generated by Django 4.2.5 on 2023-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0056_persyaratan_lelang_keterangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_itemlelang',
            name='urutan',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
