# Generated by Django 4.2.6 on 2023-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0059_alter_detail_itemlelang_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='image',
            field=models.ImageField(default=1, upload_to='upload/images/'),
            preserve_default=False,
        ),
    ]
