# Generated by Django 4.2.6 on 2024-01-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0060_pengumuman_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alamat_panitia',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='penangung_jawab_seleksi',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
