# Generated by Django 5.1.6 on 2025-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adm_lelang", "0061_alter_alamat_panitia_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="template_jadwal_seleksi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_awal", models.DateTimeField()),
                ("tanggal_akhir", models.DateTimeField()),
                ("perubahan", models.CharField(max_length=100)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Tanggal Dibuat2"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Tanggal Diubah2"),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
