# Generated by Django 5.1.6 on 2025-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adm_lelang", "0062_template_jadwal_seleksi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="undangan",
            name="file",
            field=models.FileField(
                max_length=255, upload_to="upload/files/", verbose_name="Berkas"
            ),
        ),
    ]
