# Generated by Django 5.1.6 on 2025-03-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adm_lelang", "0063_alter_undangan_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berita_acara",
            name="file",
            field=models.FileField(
                blank=True,
                default="upload/files/kosong.pdf",
                max_length=255,
                upload_to="upload/files/",
            ),
        ),
    ]
