# Generated by Django 5.1.6 on 2025-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adm_lelang", "0064_alter_berita_acara_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengumuman",
            name="dokumen",
            field=models.FileField(
                max_length=255,
                null=True,
                upload_to="upload/adm_lelang/",
                verbose_name="File Pengumuman",
            ),
        ),
    ]
