# Generated by Django 4.2.2 on 2023-06-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0004_alamat_panitia'),
        ('administrasi', '0002_ba_pemeriksaan_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ba_pemeriksaan',
            new_name='berita_acara_all',
        ),
        migrations.CreateModel(
            name='permohonan_keikutsertaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/files/')),
                ('status', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
