# Generated by Django 4.2.2 on 2023-06-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0007_alter_bidder_lelang_ip_address'),
        ('administrasi', '0006_undangan_akun'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='berita_acara_all',
            new_name='berita_acara_administrasi',
        ),
    ]
