# Generated by Django 4.2.2 on 2023-06-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0007_rename_berita_acara_all_berita_acara_administrasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara_administrasi',
            name='owner',
            field=models.TextField(blank=True, choices=[('PERMOHONAN', 'Pembukaan'), ('PEMERIKSAAN', 'Dokumen'), ('VERIFIKASI', 'Pertanyaan'), ('HASIL', 'Aanwizing'), ('SANGGAHAN', 'Simulasi'), ('AKUN', 'Akun'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100, null=True),
        ),
    ]
