# Generated by Django 4.2.2 on 2023-07-07 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0009_alter_berita_acara_administrasi_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_acara_administrasi',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita_acara_administrasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita_acara_administrasi',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita_acara_administrasi',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form_pemeriksaan',
            name='bigbond',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_pemeriksaan',
            name='sampul1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_pemeriksaan',
            name='sampul2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_sanggahan',
            name='waktu_sanggahan',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='form_verifikasi',
            name='bigbond',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_verifikasi',
            name='sampul1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hasil_evaluasi',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasil_evaluasi',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasil_evaluasi',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='agenda',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='tempat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
