# Generated by Django 4.2.2 on 2023-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0010_berita_acara_administrasi_judul_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_pemeriksaan',
            old_name='bigbond',
            new_name='bidbond',
        ),
        migrations.RenameField(
            model_name='form_verifikasi',
            old_name='bigbond',
            new_name='bidbond',
        ),
        migrations.AlterField(
            model_name='undangan_evaluasi',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undangan_sanggahan',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undangan_verifikasi',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
