# Generated by Django 4.2.2 on 2023-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0011_rename_bigbond_form_pemeriksaan_bidbond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_pemeriksaan',
            name='hasil_pemeriksaan',
            field=models.CharField(blank=True, choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada'), ('na', 'N/A')], default='na', max_length=10, null=True),
        ),
    ]
