# Generated by Django 4.2.2 on 2023-07-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0014_remove_form_evaluasi_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_sanggahan',
            name='hasil_pemeriksaan',
        ),
        migrations.AddField(
            model_name='form_sanggahan',
            name='status_sanggah',
            field=models.CharField(blank=True, choices=[('Ada', 'Sanggah'), ('Tidak Ada', 'Tidak Sanggah'), ('na', 'N/A')], default='na', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='form_sanggahan',
            name='waktu_sanggahan',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
