# Generated by Django 4.2.2 on 2023-07-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('administrasi', '0015_remove_form_sanggahan_hasil_pemeriksaan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jawaban_sanggahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_sanggah', models.CharField(blank=True, choices=[('Ada', 'Diterima'), ('Tidak Ada', 'Ditolak'), ('na', 'N/A')], default='na', max_length=10, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tindak_lanjut_seleksi', models.CharField(blank=True, choices=[('Henti', 'Dihentikan'), ('Lanjut', 'Dilanjutkan'), ('Tunda', 'Ditunda'), ('na', 'N/A')], default='na', max_length=10, null=True)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
