# Generated by Django 4.2.2 on 2023-07-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0016_jawaban_sanggahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_sanggahan',
            name='waktu_sanggahan',
        ),
    ]
