# Generated by Django 4.2.2 on 2023-07-10 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0017_remove_form_sanggahan_waktu_sanggahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_sanggahan',
            name='waktu_sanggahan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
