# Generated by Django 4.2.2 on 2023-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0018_form_sanggahan_waktu_sanggahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawaban_sanggahan',
            name='tindak_lanjut_seleksi',
            field=models.CharField(blank=True, choices=[('Henti', 'Dihentikan'), ('Lanjut', 'Dilanjutkan'), ('Tunda', 'Ditunda')], default='Tunda', max_length=10, null=True),
        ),
    ]
