# Generated by Django 4.2.2 on 2023-07-10 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0019_alter_jawaban_sanggahan_tindak_lanjut_seleksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sanggahan',
            name='waktu_sanggahan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
