# Generated by Django 4.2.2 on 2023-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0020_alter_form_sanggahan_waktu_sanggahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara_administrasi',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
