# Generated by Django 4.2.2 on 2023-07-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('administrasi', '0021_alter_berita_acara_administrasi_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
    ]
