# Generated by Django 4.2.2 on 2023-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0022_undangan_evaluasi_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan_keikutsertaan',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
