# Generated by Django 4.2.2 on 2023-07-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('administrasi', '0023_alter_permohonan_keikutsertaan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='undangan_evaluasi',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='undangan_pemeriksaan_kelengkapan',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='undangan_sanggahan',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='undangan_verifikasi',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
    ]
