# Generated by Django 4.2.2 on 2023-07-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0024_undangan_evaluasi_auctioneer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_evaluasi',
            old_name='bidder',
            new_name='nama_perusahaan',
        ),
    ]
