# Generated by Django 4.2.2 on 2023-07-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0034_menugroup_map_usermenugroup_id_perusahaan'),
        ('administrasi', '0025_rename_bidder_form_evaluasi_nama_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_acara_administrasi',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='berita_acara_administrasi',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
    ]
