# Generated by Django 4.2.2 on 2023-08-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
        ('administrasi', '0026_berita_acara_administrasi_auctioneer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan_keikutsertaan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan'),
        ),
    ]
