# Generated by Django 4.2.2 on 2023-08-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0028_alter_form_sanggahan_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_pemeriksaan',
            name='hasil_pemeriksaan',
        ),
        migrations.AddField(
            model_name='form_evaluasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form_pemeriksaan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form_verifikasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
