# Generated by Django 4.2.2 on 2023-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0029_remove_form_pemeriksaan_hasil_pemeriksaan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_kesimpulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelengkapan_sampul1', models.CharField(blank=True, max_length=10, null=True)),
                ('kelengkapan_bidbond', models.CharField(blank=True, max_length=10, null=True)),
                ('kelengkapan_sampul2', models.CharField(blank=True, max_length=10, null=True)),
                ('verifikasi_sampul1', models.CharField(blank=True, max_length=10, null=True)),
                ('verifikasi_bidbond', models.CharField(blank=True, max_length=10, null=True)),
                ('kesimpulan1', models.BooleanField(verbose_name='Hasil Pemeriksaan Kelengkapan')),
                ('kesimpulan2', models.BooleanField(verbose_name='Hasil Verifikasi')),
                ('kesimpulan3', models.BooleanField(verbose_name='Hasil Evaluasi')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='form_evaluasi',
            name='file',
            field=models.FileField(default=1, upload_to='upload/files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_pemeriksaan',
            name='bidbond',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada'), ('na', 'N/A')], default='na', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='form_pemeriksaan',
            name='sampul1',
            field=models.CharField(blank=True, choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada'), ('na', 'N/A')], default='na', max_length=10),
        ),
        migrations.AlterField(
            model_name='form_pemeriksaan',
            name='sampul2',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada'), ('na', 'N/A')], default='na', max_length=10, null=True),
        ),
    ]
