# Generated by Django 4.2.2 on 2023-08-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0030_hasil_kesimpulan_form_evaluasi_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_evaluasi',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/files/'),
        ),
    ]
