# Generated by Django 4.2.2 on 2023-08-24 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrasi', '0031_alter_form_evaluasi_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_evaluasi',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_form_evaluasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_evaluasi',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_form_evaluasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_pemeriksaan',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_form_pemeriksaan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_pemeriksaan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_form_pemeriksaan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_sanggahan',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_form_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_sanggahan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_form_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_verifikasi',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_form_verifikasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_verifikasi',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_form_verifikasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hasil_evaluasi',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_hasil_evaluasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hasil_evaluasi',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_hasil_evaluasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawaban_sanggahan',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_jawaban_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawaban_sanggahan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_jawaban_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permohonan_keikutsertaan',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_permohonan_keikutsertaan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permohonan_keikutsertaan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_permohonan_keikutsertaan', to=settings.AUTH_USER_MODEL),
        ),
    ]
