# Generated by Django 4.2.2 on 2023-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0032_form_evaluasi_dibuat_oleh_form_evaluasi_diubah_oleh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_sementara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesimpulan1', models.BooleanField(verbose_name='Hasil Pemeriksaan Kelengkapan')),
                ('kesimpulan2', models.BooleanField(verbose_name='Hasil Verifikasi')),
                ('kesimpulan3', models.BooleanField(verbose_name='Hasil Evaluasi')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='permohonan_keikutsertaan',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='upload/files/'),
        ),
        migrations.AlterField(
            model_name='permohonan_keikutsertaan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/files/'),
        ),
    ]
