# Generated by Django 4.2.2 on 2023-08-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0033_hasil_sementara_permohonan_keikutsertaan_file2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonan_keikutsertaan',
            name='pernyataan',
            field=models.TextField(blank=True, choices=[('MENGIKUTI', 'Mengikuti'), ('TIDAK_MENGIKUTI', 'Tidak Mengikuti'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100, null=True),
        ),
    ]
