# Generated by Django 4.2.2 on 2023-08-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0064_alter_bidder_perwakilan_nik_perwakilan'),
        ('administrasi', '0034_permohonan_keikutsertaan_pernyataan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_pemeriksaan',
            name='bidder',
        ),
        migrations.AddField(
            model_name='form_pemeriksaan',
            name='perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan'),
        ),
    ]
