# Generated by Django 4.2.2 on 2023-08-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0035_remove_form_pemeriksaan_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sanggahan',
            name='file',
            field=models.FileField(blank=True, default='upload/files/kosong.pdf', null=True, upload_to='upload/files/'),
        ),
    ]
