# Generated by Django 4.2.5 on 2023-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0037_alter_form_sanggahan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_sanggahan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
