# Generated by Django 4.2.6 on 2023-11-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0038_form_sanggahan_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan_keikutsertaan',
            name='pernyataan',
            field=models.TextField(blank=True, choices=[('MENGIKUTI', 'Mengikuti Seleksi Pengguna Izin Pita Frekuensi Radio'), ('TIDAK_MENGIKUTI', 'Tidak Mengikuti Seleksi Pengguna Izin Pita Frekuensi Radio'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100, null=True),
        ),
    ]
