# Generated by Django 4.2.6 on 2024-01-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0039_alter_permohonan_keikutsertaan_pernyataan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sanggahan',
            name='status_sanggah',
            field=models.CharField(blank=True, choices=[('Ada', 'Melakukan Sanggahan'), ('Tidak Ada', 'Tidak Melakukan Sanggah'), ('na', 'N/A')], default='na', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jawaban_sanggahan',
            name='jawaban_sanggah',
            field=models.CharField(blank=True, choices=[('Ada', 'Sanggahan Diterima'), ('Tidak Ada', 'Sanggahan Ditolak'), ('na', 'N/A')], default='na', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jawaban_sanggahan',
            name='tindak_lanjut_seleksi',
            field=models.CharField(blank=True, choices=[('Henti', 'Tahapan Seleksi Dihentikan'), ('Lanjut', 'Tahapan Seleksi Dilanjutkan'), ('Tunda', 'Tahapan Seleksi Ditunda')], default='Tunda', max_length=10, null=True),
        ),
    ]
