# Generated by Django 4.2.6 on 2024-06-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0069_alter_users_nama_lengkap_alter_users_user_type_and_more'),
        ('administrasi', '0040_alter_form_sanggahan_status_sanggah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonan_keikutsertaan',
            name='perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan'),
        ),
        migrations.AlterField(
            model_name='permohonan_keikutsertaan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user'),
        ),
    ]
