# Generated by Django 4.2.6 on 2024-06-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0069_alter_users_nama_lengkap_alter_users_user_type_and_more'),
        ('administrasi', '0041_permohonan_keikutsertaan_perwakilan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan_keikutsertaan',
            name='perwakilan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan'),
        ),
    ]
