# Generated by Django 4.2.2 on 2025-02-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0069_alter_users_nama_lengkap_alter_users_user_type_and_more"),
        ("administrasi", "0042_alter_permohonan_keikutsertaan_perwakilan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="undangan_evaluasi",
            name="auctioneer",
        ),
        migrations.RemoveField(
            model_name="undangan_evaluasi",
            name="bidder",
        ),
        migrations.RemoveField(
            model_name="undangan_evaluasi",
            name="item_lelang",
        ),
        migrations.RemoveField(
            model_name="undangan_pemeriksaan_kelengkapan",
            name="auctioneer",
        ),
        migrations.RemoveField(
            model_name="undangan_pemeriksaan_kelengkapan",
            name="bidder",
        ),
        migrations.RemoveField(
            model_name="undangan_pemeriksaan_kelengkapan",
            name="item_lelang",
        ),
        migrations.RemoveField(
            model_name="undangan_sanggahan",
            name="auctioneer",
        ),
        migrations.RemoveField(
            model_name="undangan_sanggahan",
            name="bidder",
        ),
        migrations.RemoveField(
            model_name="undangan_sanggahan",
            name="item_lelang",
        ),
        migrations.RemoveField(
            model_name="undangan_verifikasi",
            name="auctioneer",
        ),
        migrations.RemoveField(
            model_name="undangan_verifikasi",
            name="bidder",
        ),
        migrations.RemoveField(
            model_name="undangan_verifikasi",
            name="item_lelang",
        ),
        migrations.RemoveField(
            model_name="form_evaluasi",
            name="nama_perusahaan",
        ),
        migrations.RemoveField(
            model_name="form_pemeriksaan",
            name="perwakilan",
        ),
        migrations.AddField(
            model_name="form_evaluasi",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.AddField(
            model_name="form_pemeriksaan",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.AlterField(
            model_name="form_sanggahan",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.AlterField(
            model_name="form_sanggahan",
            name="status_sanggah",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ada", "Melakukan Sanggahan"),
                    ("Tidak Ada", "Tidak Melakukan Sanggah"),
                ],
                default="na",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="form_verifikasi",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.AlterField(
            model_name="jawaban_sanggahan",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.AlterField(
            model_name="jawaban_sanggahan",
            name="jawaban_sanggah",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ada", "Sanggahan Diterima"),
                    ("Tidak Ada", "Sanggahan Ditolak"),
                ],
                default="na",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="permohonan_keikutsertaan",
            name="bidder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.DeleteModel(
            name="undangan_akun",
        ),
        migrations.DeleteModel(
            name="undangan_evaluasi",
        ),
        migrations.DeleteModel(
            name="undangan_pemeriksaan_kelengkapan",
        ),
        migrations.DeleteModel(
            name="undangan_sanggahan",
        ),
        migrations.DeleteModel(
            name="undangan_verifikasi",
        ),
    ]
