# Generated by Django 4.2 on 2023-05-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('V', 'Viewer'), ('B', 'Bidder'), ('C', 'Auctioner')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='jenis_penyelenggara',
            field=models.CharField(choices=[('DTD', 'DINAS TETAP DARAT'), ('DBD', 'DINAS BERGERAK DARAT'), ('DPI', 'DINAS PENYIARAN'), ('DSI', 'DINAS SATELIT'), ('DMI', 'DINAS MARITIM'), ('DPB', 'DINAS PENERBANGAN')], default='DTD', max_length=3, verbose_name='Jenis Pengelenggara'),
        ),
    ]
