# Generated by Django 4.2 on 2023-05-11 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0002_users_user_type_alter_bidder_jenis_penyelenggara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='email_perusahaan',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Email Perusahaan'),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='nib_perusahaan',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='NIB Perusahaan'),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='nik',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='NIK perwakilan Perusahaan'),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='npwp_perusahaan',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='NPWP Perusahaan'),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='telp_perusahaan',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Telp Perusahaan'),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='users',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dokumen_perusahaan',
            name='dokumen',
            field=models.FileField(upload_to='upload/bidder/', verbose_name='File Dokumen'),
        ),
        migrations.AlterField(
            model_name='tim_lelang',
            name='users',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='No HP user'),
        ),
    ]
