# Generated by Django 4.2 on 2023-05-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0003_alter_bidder_email_perusahaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='alamat_perusahaan',
            field=models.TextField(max_length=2000, verbose_name='Alamat Perusahaan'),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='jabatan_di_perusahaan',
            field=models.CharField(max_length=100, verbose_name='Jabatan perwakilan di Perusahaan'),
        ),
    ]
