# Generated by Django 4.2 on 2023-05-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0004_bidder_active_alter_bidder_alamat_perusahaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tim_lelang',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='verified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
