# Generated by Django 4.2 on 2023-05-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0005_tim_lelang_active_alter_bidder_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='users',
        ),
        migrations.AddField(
            model_name='users',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
    ]
