# Generated by Django 4.2 on 2023-05-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0006_remove_bidder_users_users_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='surat_kuasa',
            field=models.FileField(default='', upload_to='uploads/bidder/', verbose_name='File Surat Kuasa'),
            preserve_default=False,
        ),
    ]
