# Generated by Django 4.2 on 2023-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0007_bidder_surat_kuasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='nik',
        ),
        migrations.AlterField(
            model_name='bidder',
            name='surat_kuasa',
            field=models.FileField(null=True, upload_to='uploads/bidder/', verbose_name='File Surat Kuasa'),
        ),
    ]
