# Generated by Django 4.2 on 2023-05-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0008_remove_bidder_nik_alter_bidder_surat_kuasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='jabatan_di_perusahaan',
        ),
        migrations.RemoveField(
            model_name='bidder',
            name='tgl_lahir',
        ),
    ]
