# Generated by Django 4.2 on 2023-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0009_remove_bidder_jabatan_di_perusahaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='masaberlaku1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='masaberlaku2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
