# Generated by Django 4.2 on 2023-05-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0011_alter_tim_lelang_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tim_lelang',
            name='users',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
