# Generated by Django 4.2 on 2023-05-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0014_bidder_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='user_id',
            field=models.CharField(max_length=30, null=True, verbose_name='user_id'),
        ),
    ]
