# Generated by Django 4.2 on 2023-05-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0017_admin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_terlihat',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='password_terlihat'),
        ),
    ]
