# Generated by Django 4.2 on 2023-05-28 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0018_users_password_terlihat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='users',
            name='masaberlaku1',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='masaberlaku2',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nama_lengkap',
            field=models.TextField(max_length=100, unique=True, verbose_name='Nama lengkap'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('V', 'Viewer'), ('B', 'Bidder'), ('C', 'Auctioner')], max_length=1),
        ),
        migrations.CreateModel(
            name='viewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_pengangkatan', models.FileField(upload_to='uploads/timlelang/', verbose_name='File SK Pengangkatan')),
                ('nip', models.CharField(max_length=30, verbose_name='NIP Anggota TIM')),
                ('jabatan_dalam_tim', models.CharField(max_length=30, verbose_name='Jabtan dalam Tim')),
                ('jabatan', models.CharField(max_length=30, verbose_name='Jabatan di UnOr yang menugaskan')),
                ('active', models.BooleanField(default=False)),
                ('users', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
