# Generated by Django 4.2 on 2023-05-29 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0021_usermenu_usermenugroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidder_perwakilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.TextField(max_length=100, unique=True, verbose_name='Nama lengkap')),
                ('email', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Email')),
                ('mobile_number', encrypted_model_fields.fields.EncryptedCharField(verbose_name='No HP user')),
                ('jabatan', models.CharField(max_length=30, verbose_name='Jabatan di UnOr yang menugaskan')),
                ('active', models.BooleanField(default=False)),
                ('users', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
