# Generated by Django 4.2 on 2023-05-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0022_bidder_perwakilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_perwakilan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='jabatan',
            field=models.CharField(max_length=30, verbose_name='Jabatan'),
        ),
    ]
