# Generated by Django 4.2 on 2023-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0023_bidder_perwakilan_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='bidder',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='users',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
