# Generated by Django 4.2 on 2023-05-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0024_alter_bidder_perwakilan_bidder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidder_perwakilan',
            old_name='bidder',
            new_name='bidder_id',
        ),
        migrations.RenameField(
            model_name='bidder_perwakilan',
            old_name='users',
            new_name='users_id',
        ),
    ]
