# Generated by Django 4.2 on 2023-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0026_alter_bidder_perwakilan_bidder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='bidder_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='users_id',
            field=models.IntegerField(blank=True),
        ),
    ]
