# Generated by Django 4.2 on 2023-05-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0027_alter_bidder_perwakilan_bidder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder_list',
            name='sk_pengangkatan',
        ),
        migrations.AddField(
            model_name='bidder_perwakilan',
            name='sk_pengangkatan',
            field=models.FileField(blank=True, upload_to='uploads/bidders/', verbose_name='File SK Pengangkatan'),
        ),
    ]
