# Generated by Django 4.2 on 2023-06-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0028_remove_bidder_list_sk_pengangkatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
