# Generated by Django 4.2 on 2023-06-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0030_jadwal_seleksi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jadwal_seleksi',
        ),
    ]
