# Generated by Django 4.2.2 on 2023-06-08 23:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0031_delete_jadwal_seleksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermenu',
            name='order',
        ),
        migrations.AddField(
            model_name='usermenu',
            name='enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='usermenu',
            name='menu_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Admin'), ('V', 'Viewer'), ('B', 'Bidder'), ('C', 'Auctioner')], max_length=4, null=True),
        ),
    ]
