# Generated by Django 4.2.2 on 2023-06-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0032_remove_usermenu_order_usermenu_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenu',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
