# Generated by Django 4.2.2 on 2023-07-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='menugroup_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='menu name')),
                ('menuid', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='usermenugroup',
            name='id_perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userman.bidder', blank=True, null=True),
            preserve_default=False,
        ),
    ]
