# Generated by Django 4.2.2 on 2023-08-01 03:35

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0035_remove_usermenugroup_id_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_perwakilan',
            name='nik_perwakilan',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='jabatan',
            field=models.CharField(blank=True, max_length=30, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='mobile_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='No HP user'),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='nama_lengkap',
            field=models.TextField(default='-', max_length=100, unique=True, verbose_name='Nama lengkap'),
        ),
    ]
