# Generated by Django 4.2.2 on 2023-08-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0036_bidder_perwakilan_nik_perwakilan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_perwakilan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bidder_perwakilan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
