# Generated by Django 4.2.2 on 2023-08-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0038_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
