# Generated by Django 4.2.2 on 2023-08-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0041_remove_bidder_user_id_admin_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder_perwakilan',
            name='users_id',
        ),
    ]
