# Generated by Django 4.2.2 on 2023-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0042_remove_bidder_perwakilan_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='nama_lengkap',
            field=models.CharField(default='-', max_length=100, unique=True, verbose_name='Nama lengkap'),
        ),
    ]
