# Generated by Django 4.2.2 on 2023-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0043_alter_bidder_perwakilan_nama_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_perwakilan',
            name='profil_peruri',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Profil Peruri'),
        ),
        migrations.AddField(
            model_name='bidder_perwakilan',
            name='ttd',
            field=models.ImageField(blank=True, upload_to='uploads/bidders/', verbose_name='Tanda Tangan Digital'),
        ),
    ]
