# Generated by Django 4.2.2 on 2023-08-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0044_bidder_perwakilan_profil_peruri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user'),
        ),
    ]
