# Generated by Django 4.2.2 on 2023-08-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0045_alter_bidder_perwakilan_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder_perwakilan_bidder', to='userman.bidder_user'),
        ),
    ]
