# Generated by Django 4.2.2 on 2023-08-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0046_alter_bidder_perwakilan_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nama_lengkap',
            field=models.TextField(max_length=100, verbose_name='Nama lengkap'),
        ),
    ]
