# Generated by Django 4.2.2 on 2023-08-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0047_alter_users_nama_lengkap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='profil_peruri',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profil Peruri'),
        ),
    ]
