# Generated by Django 4.2.2 on 2023-08-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0048_alter_bidder_perwakilan_profil_peruri'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
