# Generated by Django 4.2.2 on 2023-08-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0049_customgroup_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='customGroup',
            field=models.ManyToManyField(to='userman.customgroup'),
        ),
    ]
