# Generated by Django 4.2.2 on 2023-08-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0029_alter_bidder_lelang_bidder'),
        ('userman', '0051_alter_usermenugroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenu',
            name='tahapan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserMenu_tahapan', to='adm_lelang.tahapan_lelang2'),
        ),
    ]
