# Generated by Django 4.2.2 on 2023-08-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0053_alter_usermenu_tahapan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tim_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
