# Generated by Django 4.2.2 on 2023-08-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0054_tim_lelang_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='viewers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='viewers',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='jabatan_dalam_tim',
            field=models.CharField(choices=[('pengarah', 'Pengarah'), ('pembina', 'Pembina'), ('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('anggota', 'Anggota')], max_length=30, verbose_name='Jabtan dalam Tim'),
        ),
    ]
