# Generated by Django 4.2.2 on 2023-08-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0056_tim_lelang_created_alter_tim_lelang_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tim_lelang',
            name='jabatan_dalam_tim',
            field=models.CharField(choices=[('pengarah', 'Pengarah'), ('pembina', 'Pembina'), ('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('anggota', 'Anggota')], max_length=30, verbose_name='Jabtan dalam Tim'),
        ),
        migrations.AlterField(
            model_name='tim_lelang',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='jabatan_dalam_tim',
            field=models.CharField(choices=[('pengarah', 'Pengarah'), ('pembina', 'Pembina'), ('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('anggota', 'Anggota')], max_length=30, verbose_name='Jabtan dalam Tim'),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
