# Generated by Django 4.2.2 on 2023-08-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0057_alter_admin_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bidder',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
