# Generated by Django 4.2.2 on 2023-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0058_bidder_created_bidder_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bidder_user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
