# Generated by Django 4.2.2 on 2023-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0059_bidder_user_created_bidder_user_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='customGroup',
            field=models.ManyToManyField(blank=True, to='userman.customgroup'),
        ),
    ]
