# Generated by Django 4.2.2 on 2023-08-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenu',
            name='additional_text2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usermenu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermenu',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='additional_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
