# Generated by Django 4.2.2 on 2023-08-21 02:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0036_alter_berita_acara_file'),
        ('userman', '0061_usermenu_additional_text2_usermenu_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='tahapan',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserMenu_tahapan', to='adm_lelang.tahapan_lelang2'),
        ),
    ]
