# Generated by Django 4.2.2 on 2023-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0063_alter_bidder_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='nik_perwakilan',
            field=models.CharField(max_length=30, verbose_name='NIK'),
        ),
    ]
