# Generated by Django 4.2.2 on 2023-08-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0064_alter_bidder_perwakilan_nik_perwakilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenu',
            name='additional_text3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
