# Generated by Django 4.2.2 on 2023-08-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0065_usermenu_additional_text3'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenu',
            name='additional_text4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
