# Generated by Django 4.2.2 on 2023-08-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0066_usermenu_additional_text4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='jabatan',
            field=models.CharField(max_length=255, verbose_name='Jabatan di UnOr yang menugaskan'),
        ),
        migrations.AlterField(
            model_name='bidder_list',
            name='jabatan',
            field=models.CharField(max_length=255, verbose_name='Jabatan di UnOr yang menugaskan'),
        ),
        migrations.AlterField(
            model_name='bidder_perwakilan',
            name='jabatan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='tim_lelang',
            name='jabatan',
            field=models.CharField(max_length=255, verbose_name='Jabatan di UnOr yang menugaskan'),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='jabatan',
            field=models.CharField(max_length=255, verbose_name='Jabatan di UnOr yang menugaskan'),
        ),
    ]
