# Generated by Django 4.2.5 on 2023-10-05 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userss_dibuat_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users',
            name='diubah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userss_diubah_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
