# Generated by Django 4.2.6 on 2023-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0068_users_dibuat_oleh_users_diubah_oleh_users_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nama_lengkap',
            field=models.CharField(max_length=100, verbose_name='Nama lengkap'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('V', 'Viewer'), ('B', 'Bidder'), ('C', 'Auctioner')], max_length=30, verbose_name='Jenis User'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama user'),
        ),
    ]
