# Generated by Django 4.2.2 on 2025-02-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0069_alter_users_nama_lengkap_alter_users_user_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidder_perwakilan",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
