# Generated by Django 5.1.6 on 2025-02-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0070_bidder_perwakilan_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermenugroup",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.customgroup",
            ),
        ),
        migrations.AlterField(
            model_name="usermenugroup",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.usermenu",
            ),
        ),
    ]
