# Generated by Django 5.1.6 on 2025-02-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0071_alter_usermenugroup_group_alter_usermenugroup_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidder_perwakilan",
            name="nama_lengkap",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="Nama lengkap"
            ),
        ),
        migrations.CreateModel(
            name="Notifikasi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notifikasi",
                    models.CharField(max_length=1024, verbose_name="Notifikasi"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "email_status",
                    models.CharField(max_length=10, verbose_name="Status Email"),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bidder_nitifikasi",
                        to="userman.bidder_user",
                    ),
                ),
            ],
        ),
    ]
