# Generated by Django 5.1.6 on 2025-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0072_alter_bidder_perwakilan_nama_lengkap_notifikasi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifikasi",
            name="bidder",
        ),
        migrations.AddField(
            model_name="notifikasi",
            name="email",
            field=models.CharField(default="", max_length=50, verbose_name="Email"),
        ),
    ]
