# Generated by Django 5.1.6 on 2025-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0074_notifikasi_subyek"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifikasi",
            name="id_ba",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notifikasi",
            name="id_undangan",
            field=models.IntegerField(default=0),
        ),
    ]
