# Generated by Django 5.1.6 on 2025-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0075_notifikasi_id_ba_notifikasi_id_undangan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifikasi",
            name="email_status",
            field=models.CharField(max_length=20, verbose_name="Status Email"),
        ),
    ]
