# Generated by Django 5.1.6 on 2025-02-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userman",
            "0077_notifikasi_expire_date_notifikasi_notification_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="session_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
