# Generated by Django 5.1.6 on 2025-02-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0078_users_session_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidder_perwakilan",
            name="peruri_ttd",
            field=models.TextField(blank=True, null=True, verbose_name="ttd"),
        ),
    ]
