# Generated by Django 4.2.2 on 2023-06-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabungan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penentuan_parameter',
            name='bobot',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
