# Generated by Django 4.2.2 on 2023-06-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabungan', '0002_penentuan_parameter_bobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penentuan_parameter',
            name='p_parameter',
            field=models.CharField(max_length=100),
        ),
    ]
