# Generated by Django 4.2.2 on 2023-06-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('gabungan', '0003_alter_penentuan_parameter_p_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaian_gabungan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='penilaian_gabungan',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gabungan.penentuan_parameter'),
        ),
        migrations.AlterField(
            model_name='penentuan_parameter',
            name='p_parameter',
            field=models.CharField(max_length=100, verbose_name='Parameter'),
        ),
    ]
