# Generated by Django 4.2.2 on 2023-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabungan', '0005_alter_penilaian_gabungan_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaian_gabungan',
            name='bobot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penilaian_gabungan',
            name='penilaian',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
