# Generated by Django 4.2.2 on 2023-08-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0050_alter_undangan_unique_together'),
        ('userman', '0064_alter_bidder_perwakilan_nik_perwakilan'),
        ('gabungan', '0006_penilaian_gabungan_bobot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penentuan_parameter',
            name='p_parameter',
            field=models.CharField(choices=[('1', 'SMRA'), ('2', 'CCA'), ('3', 'Beauty Contest')], default='1', max_length=1, verbose_name='Parameter'),
        ),
        migrations.CreateModel(
            name='sum_gabungan',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sum', models.FloatField(verbose_name='Nilai Akhir')),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
