# Generated by Django 4.2.2 on 2023-09-07 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
        ('gabungan', '0007_alter_penentuan_parameter_p_parameter_sum_gabungan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penentuan_parameter',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='penilaian_gabungan',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='sum_gabungan',
            name='item_lelang',
        ),
        migrations.AddField(
            model_name='penentuan_parameter',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AddField(
            model_name='penilaian_gabungan',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AddField(
            model_name='sum_gabungan',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang'),
        ),
    ]
