# Generated by Django 4.2.2 on 2023-09-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0013_alter_sum_penilaian_options_alter_dokumen_bc_bidder_and_more'),
        ('smra2', '0023_alter_hasil_smra2_last_updated_and_more'),
        ('gabungan', '0008_remove_penentuan_parameter_item_lelang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penentuan_parameter',
            name='p_parameter',
        ),
        migrations.AddField(
            model_name='penentuan_parameter',
            name='obyek_bc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beauty_contest.obyek_seleksi_bc'),
        ),
        migrations.AddField(
            model_name='penentuan_parameter',
            name='obyek_smra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smra2.obyek_seleksi_smra'),
        ),
    ]
