# Generated by Django 4.2.2 on 2023-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabungan', '0009_remove_penentuan_parameter_p_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penentuan_parameter',
            name='bobot2',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
