# Generated by Django 4.2.2 on 2023-09-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
        ('gabungan', '0011_alter_penentuan_parameter_obyek_bc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penentuan_parameter',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang'),
        ),
    ]
