# Generated by Django 4.2.2 on 2023-09-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('gabungan', '0012_alter_penentuan_parameter_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaian_gabungan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user'),
        ),
    ]
