# Generated by Django 4.2.5 on 2023-10-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('adm_lelang', '0053_alter_pengumuman_tgl_release_alter_undangan_judul_and_more'),
        ('gabungan', '0014_hasil_gabungan'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil2_gabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('harga', models.FloatField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang')),
            ],
        ),
    ]
