# Generated by Django 4.2.5 on 2023-10-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabungan', '0015_hasil2_gabungan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil_gabungan',
            name='harga',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
