# Generated by Django 4.2.2 on 2023-07-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('userman', '0033_usermenu_order'),
        ('pasca_seleksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sanggahan_jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('judul', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('tempat', models.CharField(max_length=100)),
                ('waktu', models.DateTimeField()),
                ('agenda', models.TextField()),
                ('link_teleconference', models.TextField()),
                ('keterangan', models.TextField()),
                ('link_file', models.FileField(upload_to='upload/files/pasca_seleksi/blok/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.CreateModel(
            name='pengumuman_pemenang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('judul', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
                ('file_link', models.FileField(upload_to='upload/files/pasca_seleksi/pemenang/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.CreateModel(
            name='pemilihan_blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampul1', models.CharField(max_length=100)),
                ('bigbond', models.CharField(max_length=100)),
                ('hasil_sanggahan', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
                ('nama_perusahaan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
            ],
        ),
        migrations.CreateModel(
            name='berita_acara_pasca_seleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('judul', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('link_file', models.FileField(upload_to='upload/files/pasca_seleksi/ba/')),
                ('owner', models.TextField(blank=True, choices=[('PEMILIHAN', 'Pemilihan'), ('HASIL', 'Hasil'), ('SANGGAHAN', 'Sanggahan'), ('PENETAPAN', 'Penetapan')], default='UNKNOWN', max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
