# Generated by Django 4.2.2 on 2023-07-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('pasca_seleksi', '0002_sanggahan_jawaban_pengumuman_pemenang_pemilihan_blok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pemilihan_blok_pasca_seleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampul1', models.CharField(max_length=100)),
                ('bigbond', models.CharField(max_length=100)),
                ('sampul2', models.CharField(max_length=100)),
                ('hasil_blok', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
                ('nama_perusahaan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
            ],
        ),
    ]
