# Generated by Django 4.2.2 on 2023-07-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0004_rename_pemilihan_blok_jawaban_atas_sanggahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanggahan_jawaban',
            name='link_file',
            field=models.FileField(upload_to='upload/files/pasca_seleksi/sanggahan_jawaban/'),
        ),
    ]
