# Generated by Django 4.2.2 on 2023-07-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0005_alter_sanggahan_jawaban_link_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok',
            name='waktu',
        ),
        migrations.AlterField(
            model_name='blok',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
