# Generated by Django 4.2.2 on 2023-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0006_remove_blok_waktu_alter_blok_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blok',
            name='nomor',
            field=models.CharField(),
        ),
    ]
