# Generated by Django 4.2.2 on 2023-07-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0008_blok_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jawaban_atas_sanggahan',
            old_name='bigbond',
            new_name='bidbond',
        ),
        migrations.RenameField(
            model_name='pemilihan_blok_pasca_seleksi',
            old_name='bigbond',
            new_name='bidbond',
        ),
    ]
