# Generated by Django 4.2.2 on 2023-07-13 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0013_alter_pengumuman_tgl_release'),
        ('pasca_seleksi', '0009_rename_bigbond_jawaban_atas_sanggahan_bidbond_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='undangan_ps_sanggahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tempat', models.TextField(blank=True, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('link_teleconference', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.CreateModel(
            name='jawaban_ps_sanggahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_sanggah', models.CharField(blank=True, choices=[('Ada', 'Diterima'), ('Tidak Ada', 'Ditolak'), ('na', 'N/A')], default='na', max_length=10, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tindak_lanjut_seleksi', models.CharField(blank=True, choices=[('Henti', 'Dihentikan'), ('Lanjut', 'Dilanjutkan'), ('Tunda', 'Ditunda')], default='Tunda', max_length=10, null=True)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.CreateModel(
            name='form_ps_sanggahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sanggah', models.CharField(blank=True, choices=[('Ada', 'Sanggah'), ('Tidak Ada', 'Tidak Sanggah'), ('na', 'N/A')], default='na', max_length=10, null=True)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('waktu_sanggahan', models.DateTimeField(default=django.utils.timezone.now)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
