# Generated by Django 4.2.2 on 2023-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0010_undangan_ps_sanggahan_jawaban_ps_sanggahan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_acara_pasca_seleksi',
            name='nomor',
            field=models.CharField(),
        ),
    ]
