# Generated by Django 4.2.2 on 2023-07-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('pasca_seleksi', '0012_berita_acara_pasca_seleksi_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanggahan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
    ]
