# Generated by Django 4.2.2 on 2023-07-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('pasca_seleksi', '0015_alter_form_ps_sanggahan_waktu_sanggahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='undangan_ps_sanggahan',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
    ]
