# Generated by Django 4.2.2 on 2023-07-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0013_alter_pengumuman_tgl_release'),
        ('pasca_seleksi', '0016_undangan_ps_sanggahan_auctioneer'),
    ]

    operations = [
        migrations.CreateModel(
            name='blok_pasca_seleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_block', models.CharField(max_length=100)),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.RemoveField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='nama_perusahaan',
        ),
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder', verbose_name='Nama Perusahaan'),
        ),
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='jatah_block',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='item_lelang',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='hasil_blok_pasca_seleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dipilih', models.BooleanField(verbose_name=False)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasca_seleksi.blok_pasca_seleksi')),
                ('pilih_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasca_seleksi.pemilihan_blok_pasca_seleksi')),
            ],
        ),
    ]
