# Generated by Django 4.2.2 on 2023-07-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0018_pemilihan_blok_pasca_seleksi_pilih_blok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='penawaran',
            field=models.FloatField(null=True, verbose_name='Penawaran'),
        ),
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='persetujuan',
            field=models.BooleanField(default=False, verbose_name='Persetujuan'),
        ),
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='sudah_pilih',
            field=models.BooleanField(default=False, verbose_name='Sudah Memilih'),
        ),
        migrations.AlterField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='jatah_block',
            field=models.IntegerField(null=True, verbose_name='Jatah Blok'),
        ),
        migrations.AlterField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='pilih_blok',
            field=models.BooleanField(default=False, verbose_name='Pilih Blok'),
        ),
    ]
