# Generated by Django 4.2.2 on 2023-07-26 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0014_template_bertia_acara'),
        ('pasca_seleksi', '0020_pemilihan_blok_pasca_seleksi_max_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok_pasca_seleksi',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AlterField(
            model_name='blok_pasca_seleksi',
            name='item_lelang',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='max_block',
            field=models.IntegerField(null=True, verbose_name='Maks Blok'),
        ),
    ]
