# Generated by Django 4.2.2 on 2023-07-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('pasca_seleksi', '0021_blok_pasca_seleksi_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok_pasca_seleksi',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder', verbose_name='Nama Perusahaan'),
        ),
    ]
