# Generated by Django 4.2.2 on 2023-07-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('pasca_seleksi', '0022_blok_pasca_seleksi_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok_pasca_seleksi',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Disetujui'),
        ),
        migrations.AddField(
            model_name='blok_pasca_seleksi',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang', verbose_name='Tim Lelang'),
        ),
    ]
