# Generated by Django 4.2.2 on 2023-07-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0024_blok_pasca_seleksi_pilih_blok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok_pasca_seleksi',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
