# Generated by Django 4.2.2 on 2023-07-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('pasca_seleksi', '0025_blok_pasca_seleksi_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemenang',
            name='nama_perusahaan',
        ),
        migrations.AddField(
            model_name='pemenang',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder', verbose_name='Nama Perusahaan'),
        ),
        migrations.AddField(
            model_name='pemenang',
            name='judul',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pemenang',
            name='nomor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pemenang',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
