# Generated by Django 4.2.2 on 2023-09-13 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasca_seleksi', '0027_alter_blok_pasca_seleksi_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_ps_sanggahan',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_form_ps_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_ps_sanggahan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_form_ps_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form_ps_sanggahan',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_perwakilan'),
        ),
    ]
