# Generated by Django 4.2.2 on 2023-09-13 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0028_form_ps_sanggahan_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_ps_sanggahan',
            name='waktu_sanggahan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
