# Generated by Django 4.2.2 on 2023-09-13 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasca_seleksi', '0029_alter_form_ps_sanggahan_waktu_sanggahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawaban_ps_sanggahan',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_jawaban_ps_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawaban_ps_sanggahan',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_jawaban_ps_sanggahan', to=settings.AUTH_USER_MODEL),
        ),
    ]
