# Generated by Django 4.2.2 on 2023-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('pasca_seleksi', '0030_jawaban_ps_sanggahan_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemenang',
            name='auctioneer',
            field=models.ManyToManyField(blank=True, to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='pemenang',
            name='viewer',
            field=models.ManyToManyField(blank=True, to='userman.viewers'),
        ),
        migrations.RemoveField(
            model_name='pemenang',
            name='bidder',
        ),
        migrations.AddField(
            model_name='pemenang',
            name='bidder',
            field=models.ManyToManyField(blank=True, to='userman.bidder_user'),
        ),
    ]
