# Generated by Django 4.2.2 on 2023-09-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0031_pemenang_auctioneer_pemenang_viewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='bidbond',
        ),
        migrations.RemoveField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='hasil_blok',
        ),
        migrations.RemoveField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='jatah_block',
        ),
        migrations.RemoveField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='max_block',
        ),
        migrations.RemoveField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='sampul1',
        ),
        migrations.RemoveField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='sampul2',
        ),
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
