# Generated by Django 4.2.2 on 2023-09-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('pasca_seleksi', '0032_remove_pemilihan_blok_pasca_seleksi_bidbond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user', verbose_name='Nama Perusahaan'),
        ),
    ]
