# Generated by Django 4.2.2 on 2023-09-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0033_alter_pemilihan_blok_pasca_seleksi_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok_pasca_seleksi',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='blok_pasca_seleksi',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='blok_pasca_seleksi',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='blok_pasca_seleksi',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='blok_pasca_seleksi',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='blok_pasca_seleksi',
            name='pilih_blok',
        ),
        migrations.RemoveField(
            model_name='blok_pasca_seleksi',
            name='sudah_pilih',
        ),
        migrations.AddField(
            model_name='pemilihan_blok_pasca_seleksi',
            name='blok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasca_seleksi.blok_pasca_seleksi'),
        ),
    ]
