# Generated by Django 4.2.2 on 2023-09-15 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasca_seleksi', '0034_remove_blok_pasca_seleksi_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemenang',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh_pemenang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pemenang',
            name='diubah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diubah_oleh_pemenang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pemenang',
            name='tanggal',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Penetapan'),
        ),
    ]
