# Generated by Django 4.2.5 on 2023-10-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0036_pemilihan_blok_pasca_seleksi_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_ps_sanggahan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
