# Generated by Django 4.2.6 on 2024-01-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasca_seleksi', '0038_sanggahan_bidder_sanggahan_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawaban_ps_sanggahan',
            name='jawaban_sanggah',
            field=models.CharField(blank=True, choices=[('Diterima', 'Diterima'), ('Ditolak', 'Ditolak'), ('na', 'N/A')], default='na', max_length=10, null=True),
        ),
    ]
