# Generated by Django 4.2.2 on 2025-02-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0069_alter_users_nama_lengkap_alter_users_user_type_and_more"),
        ("pasca_seleksi", "0039_alter_jawaban_ps_sanggahan_jawaban_sanggah"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form_ps_sanggahan",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.AlterField(
            model_name="form_ps_sanggahan",
            name="status_sanggah",
            field=models.CharField(
                blank=True,
                choices=[("Ada", "Sanggah"), ("Tidak Ada", "Tidak Sanggah")],
                default="na",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jawaban_ps_sanggahan",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userman.bidder_user",
            ),
        ),
        migrations.AlterField(
            model_name="jawaban_ps_sanggahan",
            name="jawaban_sanggah",
            field=models.CharField(
                blank=True,
                choices=[("Diterima", "Diterima"), ("Ditolak", "Ditolak")],
                default="na",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jawaban_ps_sanggahan",
            name="tindak_lanjut_seleksi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Berhenti", "Berhenti"),
                    ("Lanjut", "Lanjut"),
                    ("Berhenti Sementara", "Berhenti Sementara"),
                ],
                default="Lanjut",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sanggahan",
            name="status_sanggahan",
            field=models.CharField(
                blank=True,
                choices=[("Ada", "Sanggah"), ("Tidak Ada", "Tidak Sanggah")],
                default="na",
                max_length=10,
                null=True,
            ),
        ),
    ]
