# Generated by Django 5.1.6 on 2025-03-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pasca_seleksi", "0040_alter_form_ps_sanggahan_bidder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jawaban_ps_sanggahan",
            name="file",
            field=models.FileField(max_length=255, upload_to="upload/files/"),
        ),
    ]
