# Generated by Django 5.1.6 on 2025-03-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pasca_seleksi", "0041_alter_jawaban_ps_sanggahan_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pemenang",
            name="file_link",
            field=models.FileField(
                max_length=255, upload_to="upload/files/pasca_seleksi/pemenang/"
            ),
        ),
    ]
