# Generated by Django 4.2.2 on 2023-07-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0012_alter_item_lelang_tayang'),
        ('userman', '0033_usermenu_order'),
        ('negosiasi', '0002_alter_penawaran_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ba_nego',
            name='judul',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ba_nego',
            name='nomor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ba_nego',
            name='owner',
            field=models.TextField(blank=True, choices=[('SAMPUL2', 'sampul2'), ('EVSAMPUL2', 'evaluasisampul2'), ('REVSAMPUL2', 'revsampul2'), ('EVREVSAMPUL2', 'evaluasirevsampul2'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ba_nego',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='undg_esampul2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('tempat', models.TextField(blank=True, null=True)),
                ('agenda', models.CharField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('link_teleconference', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='upload/files/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.CreateModel(
            name='form_esampul2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampul2', models.CharField(blank=True, max_length=100, null=True)),
                ('sampul1', models.CharField(blank=True, choices=[('Lengkap', 'Lengkap'), ('Tidak Lengkap', 'Tidak Lengkap')], max_length=110, null=True)),
                ('bid_bond', models.CharField(blank=True, choices=[('Sah', 'Sah'), ('Tidak Sah', 'Tidak Sah')], max_length=100, null=True)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
