# Generated by Django 4.2.2 on 2023-07-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0003_ba_nego_judul_ba_nego_nomor_ba_nego_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ba_nego',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
