# Generated by Django 4.2.2 on 2023-07-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0004_ba_nego_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_esampul2',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
