# Generated by Django 4.2.2 on 2023-07-10 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0005_form_esampul2_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_esampul2',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
