# Generated by Django 4.2.2 on 2023-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0009_alter_ba_nego_tanggal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_esampul2',
            old_name='bidder',
            new_name='nama_perusahaan',
        ),
        migrations.RemoveField(
            model_name='form_esampul2',
            name='bid_bond',
        ),
        migrations.RemoveField(
            model_name='form_esampul2',
            name='sampul1',
        ),
        migrations.AlterField(
            model_name='form_esampul2',
            name='sampul2',
            field=models.CharField(blank=True, choices=[('Diterima', 'Sesuai'), ('Tidak Diterima', 'Tidak Sesuai')], max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='form_evaluasi_revsampul2',
            name='sampul2',
            field=models.CharField(blank=True, choices=[('Diterima', 'Sesuai'), ('Tidak Diterima', 'Tidak Sesuai')], max_length=110, null=True),
        ),
    ]
