# Generated by Django 4.2.2 on 2023-07-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0010_rename_bidder_form_esampul2_nama_perusahaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_esampul2',
            name='sampul2',
            field=models.CharField(blank=True, choices=[('Diterima', 'Diterima'), ('Tidak Diterima', 'Tidak Diterima')], max_length=110, null=True),
        ),
    ]
