# Generated by Django 4.2.2 on 2023-07-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0011_alter_form_esampul2_sampul2'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_esampul2',
            name='verifikasi',
            field=models.CharField(blank=True, choices=[('Sesuai', 'Sesuai'), ('Tidak Sesuai', 'Tidak Sesuai')], max_length=110, null=True),
        ),
    ]
