# Generated by Django 4.2.2 on 2023-07-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0013_remove_form_esampul2_verifikasi_sampul2_verifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_revsampul2',
            name='verifikasi',
            field=models.CharField(blank=True, choices=[('Sesuai', 'Sesuai'), ('Tidak Sesuai', 'Tidak Sesuai')], max_length=110, null=True),
        ),
    ]
