# Generated by Django 4.2.2 on 2023-07-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0014_form_revsampul2_verifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_evaluasi_revsampul2',
            name='sampul2',
            field=models.CharField(blank=True, choices=[('Diterima', 'Diterima'), ('Tidak Diterima', 'Tidak Diterima')], max_length=110, null=True),
        ),
    ]
