# Generated by Django 4.2.2 on 2023-07-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0015_alter_form_evaluasi_revsampul2_sampul2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ba_nego',
            old_name='dokumen_ba',
            new_name='dokumen_BA',
        ),
    ]
