# Generated by Django 4.2.2 on 2023-07-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0016_rename_dokumen_ba_ba_nego_dokumen_ba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_esampul2',
            old_name='sampul2',
            new_name='sampul_2',
        ),
        migrations.RenameField(
            model_name='form_evaluasi_revsampul2',
            old_name='sampul2',
            new_name='sampul_2',
        ),
        migrations.RenameField(
            model_name='form_revsampul2',
            old_name='sampul2',
            new_name='sampul_2',
        ),
        migrations.RenameField(
            model_name='sampul2',
            old_name='sampul2',
            new_name='sampul_2',
        ),
    ]
