# Generated by Django 4.2.2 on 2023-07-31 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('negosiasi', '0019_undg_esampul2_auctioneer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ba_nego',
            name='auctioneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='ba_nego',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
    ]
