# Generated by Django 4.2.2 on 2023-08-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0037_bidder_perwakilan_created_and_more'),
        ('negosiasi', '0020_ba_nego_auctioneer_ba_nego_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undangan_revsampul2',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='undangan_revsampul2',
            name='bidder',
        ),
        migrations.AlterField(
            model_name='undangan_revsampul2',
            name='link_teleconference',
            field=models.TextField(blank=True, null=True, verbose_name='Link Teleconference'),
        ),
        migrations.AddField(
            model_name='undangan_revsampul2',
            name='auctioneer',
            field=models.ManyToManyField(to='userman.tim_lelang'),
        ),
        migrations.AddField(
            model_name='undangan_revsampul2',
            name='bidder',
            field=models.ManyToManyField(to='userman.bidder'),
        ),
    ]
