# Generated by Django 4.2.2 on 2023-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0064_alter_bidder_perwakilan_nik_perwakilan'),
        ('negosiasi', '0021_remove_undangan_revsampul2_auctioneer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undangan_revsampul2',
            name='auctioneer',
            field=models.ManyToManyField(to='userman.tim_lelang', verbose_name='Auctioneer'),
        ),
        migrations.AlterField(
            model_name='undangan_revsampul2',
            name='bidder',
            field=models.ManyToManyField(to='userman.bidder', verbose_name='Bidder'),
        ),
    ]
