# Generated by Django 4.2.2 on 2023-09-06 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negosiasi', '0022_alter_undangan_revsampul2_auctioneer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluasi_penawaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil', models.CharField(blank=True, choices=[('Diterima', 'Diterima'), ('Tidak Diterima', 'Tidak Diterima')], max_length=110, null=True)),
                ('catatan', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_esampul_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_esampul_diubah_oleh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='evaluasi_revisi_penawaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil', models.CharField(blank=True, choices=[('Diterima', 'Diterima'), ('Tidak Diterima', 'Tidak Diterima')], max_length=110, null=True)),
                ('catatan', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_rsampul_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_rsampul_diubah_oleh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='obyek_seleksi_nego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bidder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user', verbose_name='Bidder')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_obyek_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_obyek_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang', verbose_name='Obyek Seleksi')),
            ],
        ),
        migrations.CreateModel(
            name='revisi_penawaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokumen_penawaran', models.FileField(upload_to='upload/files/')),
                ('harga', models.FloatField()),
                ('blok', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_rpenawaran_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_rpenawaran_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang')),
                ('perwakilan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_perwakilan')),
            ],
        ),
        migrations.RemoveField(
            model_name='form_esampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='form_esampul2',
            name='nama_perusahaan',
        ),
        migrations.RemoveField(
            model_name='form_evaluasi_revsampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='form_evaluasi_revsampul2',
            name='nama_perusahaan',
        ),
        migrations.RemoveField(
            model_name='form_revsampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='form_revsampul2',
            name='nama_perusahaan',
        ),
        migrations.RemoveField(
            model_name='sampul2',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='sampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='undangan_evaluasi_revsampul2',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='undangan_evaluasi_revsampul2',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='undangan_evaluasi_revsampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='undangan_revsampul2',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='undangan_revsampul2',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='undangan_revsampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='undg_esampul2',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='undg_esampul2',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='undg_esampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='undg_sampul2',
            name='auctioneer',
        ),
        migrations.RemoveField(
            model_name='undg_sampul2',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='undg_sampul2',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='penawaran',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='penawaran',
            name='penawaran',
        ),
        migrations.AddField(
            model_name='penawaran',
            name='blok',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penawaran',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_penawaran_dibuat_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penawaran',
            name='diubah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_penawaran_diubah_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penawaran',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AddField(
            model_name='penawaran',
            name='perwakilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_perwakilan'),
        ),
        migrations.AlterField(
            model_name='penawaran',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user'),
        ),
        migrations.AlterField(
            model_name='penawaran',
            name='harga',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='ba_nego',
        ),
        migrations.DeleteModel(
            name='form_esampul2',
        ),
        migrations.DeleteModel(
            name='form_evaluasi_revsampul2',
        ),
        migrations.DeleteModel(
            name='form_revsampul2',
        ),
        migrations.DeleteModel(
            name='sampul2',
        ),
        migrations.DeleteModel(
            name='undangan_evaluasi_revsampul2',
        ),
        migrations.DeleteModel(
            name='undangan_revsampul2',
        ),
        migrations.DeleteModel(
            name='undg_esampul2',
        ),
        migrations.DeleteModel(
            name='undg_sampul2',
        ),
        migrations.AddField(
            model_name='evaluasi_revisi_penawaran',
            name='revisi_penawaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negosiasi.revisi_penawaran'),
        ),
        migrations.AddField(
            model_name='evaluasi_penawaran',
            name='penawaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negosiasi.penawaran'),
        ),
    ]
