# Generated by Django 4.2.2 on 2023-09-06 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negosiasi', '0023_evaluasi_penawaran_evaluasi_revisi_penawaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penawaran',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penawaran',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
