# Generated by Django 4.2.2 on 2023-09-06 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0024_penawaran_verified_penawaran_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='penawaran',
            name='verified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
