# Generated by Django 4.2.2 on 2023-09-06 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negosiasi', '0025_penawaran_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisi_penawaran',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revisi_penawaran',
            name='verified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisi_penawaran',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nego_rev_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluasi_penawaran',
            name='penawaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negosiasi.penawaran'),
        ),
    ]
