# Generated by Django 4.2.5 on 2023-10-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('adm_lelang', '0053_alter_pengumuman_tgl_release_alter_undangan_judul_and_more'),
        ('negosiasi', '0028_obyek_seleksi_nego_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_negosiasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang')),
            ],
        ),
    ]
