# Generated by Django 4.2.5 on 2023-10-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negosiasi', '0029_hasil_negosiasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisi_penawaran',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
