# Generated by Django 4.2.2 on 2023-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0001_initial'),
    ]

    operations = [
    ]
