# Generated by Django 4.2.2 on 2023-07-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('smra2', '0002_signature_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='signature2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttd', models.ImageField(upload_to='upload/signature')),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
            ],
        ),
    ]
