# Generated by Django 4.2.2 on 2023-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0003_signature2_delete_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature2',
            name='uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
