# Generated by Django 4.2.2 on 2023-07-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0013_alter_pengumuman_tgl_release'),
        ('smra2', '0005_price_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_increase',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang'),
        ),
    ]
