# Generated by Django 4.2.2 on 2023-07-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0007_remove_price_increase_rentang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_smra2',
            name='berita_acara',
            field=models.FileField(default=1, upload_to='upload/bidder'),
            preserve_default=False,
        ),
    ]
