# Generated by Django 4.2.2 on 2023-07-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0008_round_smra2_berita_acara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_smra2',
            name='berita_acara',
        ),
        migrations.AddField(
            model_name='hasil_smra2',
            name='berita_acara',
            field=models.FileField(default=1, upload_to='upload/bidder'),
            preserve_default=False,
        ),
    ]
