# Generated by Django 4.2.2 on 2023-07-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0009_remove_round_smra2_berita_acara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature2',
            name='profileName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
