# Generated by Django 4.2.2 on 2023-07-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0010_signature2_profilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctioner_hasil',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(verbose_name='Putaran')),
                ('item_lelang', models.IntegerField()),
                ('block', models.IntegerField()),
                ('harga', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='hasil_highest',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_lelang', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True, verbose_name='Harga')),
                ('round', models.FloatField(null=True, verbose_name='Putaran')),
                ('block', models.FloatField(null=True, verbose_name='Jumlah Blok')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='hasil_smra2',
            name='jenis',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('KHUSUS', 'KHUSUS')], default='NORMAL', max_length=6),
        ),
        migrations.AlterField(
            model_name='signature2',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
