# Generated by Django 4.2.2 on 2023-08-19 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
        ('adm_lelang', '0034_tahapan_lelang2_orderby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smra2', '0011_auctioner_hasil_hasil_highest_hasil_smra2_jenis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='obyek_seleksi_smra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bidder_user', models.ManyToManyField(to='userman.bidder_user')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smra_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smra_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang')),
            ],
        ),
    ]
