# Generated by Django 4.2.2 on 2023-08-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
        ('adm_lelang', '0034_tahapan_lelang2_orderby'),
        ('smra2', '0012_obyek_seleksi_smra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasil_smra2',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user'),
        ),
        migrations.AlterField(
            model_name='obyek_seleksi_smra',
            name='bidder_user',
            field=models.ManyToManyField(to='userman.bidder_user', verbose_name='Bidder'),
        ),
        migrations.AlterField(
            model_name='obyek_seleksi_smra',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang', verbose_name='Obyek Seleksi'),
        ),
        migrations.AlterField(
            model_name='round_smra2',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user'),
        ),
    ]
