# Generated by Django 4.2.2 on 2023-08-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0034_tahapan_lelang2_orderby'),
        ('userman', '0060_alter_users_customgroup'),
        ('smra2', '0013_alter_hasil_smra2_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='is_block_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='obyek_seleksi_smra',
            name='bidder_user',
        ),
        migrations.RemoveField(
            model_name='obyek_seleksi_smra',
            name='item',
        ),
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='bidder_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user', verbose_name='Bidder'),
        ),
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='item',
            field=models.ManyToManyField(to='adm_lelang.detail_itemlelang', verbose_name='Obyek Seleksi'),
        ),
    ]
