# Generated by Django 4.2.2 on 2023-08-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
        ('adm_lelang', '0035_berita_acara_viewer_undangan_viewer_and_more'),
        ('smra2', '0015_round_smra2_perwakilan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='blok_awal',
            field=models.IntegerField(blank=True, default=0, verbose_name='Blok Awal'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='obyek_seleksi_smra',
            name='bidder_user',
        ),
        migrations.RemoveField(
            model_name='obyek_seleksi_smra',
            name='item',
        ),
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='bidder_user',
            field=models.ManyToManyField(to='userman.bidder_user', verbose_name='Bidder'),
        ),
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang', verbose_name='Obyek Seleksi'),
        ),
    ]
