# Generated by Django 4.2.2 on 2023-08-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0060_alter_users_customgroup'),
        ('smra2', '0016_obyek_seleksi_smra_blok_awal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obyek_seleksi_smra',
            name='bidder_user',
        ),
        migrations.AddField(
            model_name='obyek_seleksi_smra',
            name='bidder_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user', verbose_name='Bidder'),
        ),
    ]
