# Generated by Django 4.2.2 on 2023-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0017_remove_obyek_seleksi_smra_bidder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil_smra2',
            name='berita_acara_unsigned',
            field=models.FileField(blank=True, upload_to='upload/bidder'),
        ),
    ]
