# Generated by Django 4.2.2 on 2023-08-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0063_alter_bidder_active'),
        ('smra2', '0018_hasil_smra2_berita_acara_unsigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil_smra2',
            name='perwakilan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_perwakilan'),
        ),
    ]
