# Generated by Django 4.2.2 on 2023-08-29 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smra2', '0019_hasil_smra2_perwakilan'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_auctioner_maxmin',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(verbose_name='Putaran')),
                ('item_lelang', models.IntegerField()),
                ('block', models.IntegerField()),
                ('harga_max', models.FloatField()),
                ('harga_min', models.FloatField()),
                ('block_max', models.FloatField()),
                ('block_min', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='price_increase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dibuat Pertama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price_increase',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_increase_dibuat_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price_increase',
            name='diubah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_increase_diubah_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price_increase',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir'),
        ),
    ]
