# Generated by Django 4.2.2 on 2023-08-31 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
        ('smra2', '0020_hasil_auctioner_maxmin_price_increase_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_increase',
            name='detail_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang'),
        ),
    ]
