# Generated by Django 4.2.2 on 2023-09-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0022_hasil_smra2_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasil_smra2',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hasil_smra2',
            name='submit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
