# Generated by Django 4.2.2 on 2023-09-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
        ('smra2', '0023_alter_hasil_smra2_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil2_smra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.FloatField()),
                ('item_lelang', models.IntegerField(null=True)),
                ('submit', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('penawaran', models.FloatField(null=True)),
                ('valid', models.BooleanField(default=False)),
                ('jenis', models.CharField(choices=[('NORMAL', 'NORMAL'), ('KHUSUS', 'KHUSUS')], default='NORMAL', max_length=6)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang')),
                ('perwakilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_perwakilan')),
            ],
        ),
    ]
