# Generated by Django 4.2.2 on 2023-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0024_hasil2_smra'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil2_smra',
            name='ranking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hasil2_smra',
            name='submit',
            field=models.DateTimeField(null=True),
        ),
    ]
