# Generated by Django 4.2.2 on 2023-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0026_alter_hasil2_smra_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil2_smra',
            name='ranking_putaran',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
