# Generated by Django 4.2.2 on 2023-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0027_hasil2_smra_ranking_putaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil2_smra',
            name='berlaku',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hasil_smra2',
            name='berlaku',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='round_smra2',
            name='ext_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
