# Generated by Django 4.2.2 on 2023-10-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0028_hasil2_smra_berlaku_hasil_smra2_berlaku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil2_smra',
            name='mulai',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hasil2_smra',
            name='selesai',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hasil_smra2',
            name='mulai',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hasil_smra2',
            name='selesai',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='price_increase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='price_increase',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.DeleteModel(
            name='signature2',
        ),
    ]
