# Generated by Django 4.2.6 on 2024-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smra2', '0029_hasil2_smra_mulai_hasil2_smra_selesai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil_smra2',
            name='fin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round_smra2',
            name='vi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='round_smra2',
            name='status_round',
            field=models.CharField(choices=[('STA', 'START'), ('STO', 'STOP'), ('SUS', 'SUSPEND'), ('CLO', 'CLOSED'), ('FIN', 'FINAL'), ('INI', 'INIT'), ('NON', 'NONE'), ('WAI', 'WAIT'), ('NSC', 'NOSCHEDULE')], default='NON', max_length=3),
        ),
    ]
