# Generated by Django 5.1.6 on 2025-02-26 09:37

import django.db.models.deletion
import smra2.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adm_lelang", "0062_template_jadwal_seleksi"),
        ("smra2", "0031_alter_hasil2_smra_bidder_alter_hasil2_smra_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="round_schedule_smra2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mulai", models.TimeField()),
                ("selesai", models.TimeField()),
                (
                    "hari",
                    smra2.models.DayOfTheWeekField(
                        choices=[
                            ("1", "Senin"),
                            ("2", "Selasa"),
                            ("3", "Rabu"),
                            ("4", "Kamis"),
                            ("5", "Jumat"),
                            ("6", "Sabtu"),
                            ("7", "Minggu"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Diubah Terakhir"),
                ),
                (
                    "dibuat_oleh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_schedule2_dibuat_oleh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_schedule2_diubah_oleh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="adm_lelang.item_lelang",
                    ),
                ),
            ],
        ),
    ]
