# Generated by Django 5.1.6 on 2025-03-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smra2", "0032_round_schedule_smra2"),
    ]

    operations = [
        migrations.AddField(
            model_name="round_smra2",
            name="otp",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hasil_smra2",
            name="submit",
            field=models.DateTimeField(null=True),
        ),
    ]
