# Generated by Django 4.2.2 on 2023-06-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_evaluasi',
            name='bobot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parameter_evaluasi',
            name='parameter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
