# Generated by Django 4.2.2 on 2023-06-23 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('beauty_contest', '0002_parameter_evaluasi_bobot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaian_bc',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder'),
        ),
        migrations.AddField(
            model_name='penilaian_bc',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beauty_contest.parameter_evaluasi'),
        ),
    ]
