# Generated by Django 4.2.2 on 2023-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0004_berita_acara_bc_auctioneer_berita_acara_bc_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman_bc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/files/'),
        ),
    ]
