# Generated by Django 4.2.2 on 2023-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0005_pengumuman_bc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaian_bc',
            name='bobot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
