# Generated by Django 4.2.2 on 2023-07-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0033_usermenu_order'),
        ('adm_lelang', '0013_alter_pengumuman_tgl_release'),
        ('beauty_contest', '0006_penilaian_bc_bobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaian_bc',
            name='penilaian',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='sum_penilaian',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item_lelang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
