# Generated by Django 4.2.2 on 2023-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0008_obyek_seleksi_bc_format_dokumen_bc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obyek_seleksi_bc',
            name='blok_awal',
        ),
        migrations.RemoveField(
            model_name='obyek_seleksi_bc',
            name='ipaddress',
        ),
        migrations.RemoveField(
            model_name='obyek_seleksi_bc',
            name='is_block_ip',
        ),
    ]
