# Generated by Django 4.2.2 on 2023-09-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beauty_contest', '0009_remove_obyek_seleksi_bc_blok_awal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen_bc',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='format_dokumen_bc',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='parameter_evaluasi',
            name='item_lelang',
        ),
        migrations.RemoveField(
            model_name='penilaian_bc',
            name='item_lelang',
        ),
        migrations.AddField(
            model_name='dokumen_bc',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_bc_dibuat_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dokumen_bc',
            name='diubah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_bc_diubah_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dokumen_bc',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AddField(
            model_name='format_dokumen_bc',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AddField(
            model_name='parameter_evaluasi',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AddField(
            model_name='penilaian_bc',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_bc_dibuat_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penilaian_bc',
            name='diubah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_bc_diubah_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penilaian_bc',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_lelang.detail_itemlelang'),
        ),
    ]
