# Generated by Django 4.2.2 on 2023-09-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0010_remove_dokumen_bc_item_lelang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengumuman_bc',
            name='item_lelang',
        ),
        migrations.AddField(
            model_name='format_dokumen_bc',
            name='format_xls',
            field=models.FileField(default=None, upload_to='upload/files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format_dokumen_bc',
            name='judul',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='berita_acara_bc',
        ),
        migrations.DeleteModel(
            name='pengumuman_bc',
        ),
    ]
