# Generated by Django 4.2.2 on 2023-09-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('beauty_contest', '0012_format_dokumen_bc_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sum_penilaian',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='dokumen_bc',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user'),
        ),
        migrations.AlterField(
            model_name='penilaian_bc',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userman.bidder_user'),
        ),
    ]
