# Generated by Django 4.2.2 on 2023-09-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0013_alter_sum_penilaian_options_alter_dokumen_bc_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='format_dokumen_bc',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
