# Generated by Django 4.2.5 on 2023-10-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0068_users_dibuat_oleh_users_diubah_oleh_users_pending'),
        ('beauty_contest', '0015_obyek_seleksi_bc_block_hasil_beauty_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen_bc',
            name='perwakilan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_perwakilan'),
        ),
    ]
