# Generated by Django 4.2.5 on 2023-10-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0016_dokumen_bc_perwakilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen_bc',
            name='nama_dok',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
