# Generated by Django 4.2.5 on 2023-10-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0018_format_dokumen_bc_nomor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format_dokumen_bc',
            name='tgl_penetapan',
            field=models.DateTimeField(),
        ),
    ]
