# Generated by Django 4.2.5 on 2023-10-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0019_alter_format_dokumen_bc_tgl_penetapan'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaian_bc',
            name='hasil_evaluasi',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='penilaian_bc',
            name='keterangan',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
