# Generated by Django 4.2.5 on 2023-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_contest', '0020_penilaian_bc_hasil_evaluasi_penilaian_bc_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaian_bc',
            name='hasil_evaluasi',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
