# Generated by Django 4.2.2 on 2023-07-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_cca',
            name='eli_point',
            field=models.IntegerField(null=True),
        ),
    ]
