# Generated by Django 4.2.2 on 2023-08-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0021_pengumuman_diubah_oleh'),
        ('cca', '0003_round_sum_round_cca_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_highest_cca',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_lelang', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True, verbose_name='Harga')),
                ('round', models.FloatField(null=True, verbose_name='Putaran')),
                ('block', models.FloatField(null=True, verbose_name='Jumlah Blok')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='hasil_highest_smra',
        ),
        migrations.DeleteModel(
            name='round_sum',
        ),
        migrations.DeleteModel(
            name='sum_round_cca',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='item',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='max_block',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='penawaran',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='prev_block',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='prev_price',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='spectrum_cap',
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='activity',
            field=models.IntegerField(null=True, verbose_name='Aktivitas'),
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='block',
            field=models.IntegerField(null=True, verbose_name='Blok'),
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='eli_point',
            field=models.IntegerField(null=True, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='item_lelang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang', verbose_name='Judul Seleksi'),
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='price',
            field=models.FloatField(null=True, verbose_name='Harga'),
        ),
    ]
