# Generated by Django 4.2.2 on 2023-08-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0040_remove_bidder_perwakilan_bidder_id_and_more'),
        ('adm_lelang', '0021_pengumuman_diubah_oleh'),
        ('cca', '0004_hasil_highest_cca_delete_hasil_highest_smra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasil_cca',
            name='jenis',
            field=models.CharField(choices=[('CLOCK', 'CLOCK'), ('SUPLE', 'SUPLEMENTAL'), ('ASSI', 'ASSIGNMENT')], default='CLOCK', max_length=5),
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='jenis',
            field=models.CharField(choices=[('CLOCK', 'CLOCK'), ('SUPLE', 'SUPLEMENTAL'), ('ASSI', 'ASSIGNMENT')], default='CLOCK', max_length=5),
        ),
        migrations.CreateModel(
            name='round_detail_cca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('block', models.IntegerField()),
                ('prev_price', models.FloatField()),
                ('prev_block', models.IntegerField()),
                ('eli_per_block', models.IntegerField()),
                ('spectrum_cap', models.IntegerField()),
                ('max_blok', models.IntegerField()),
                ('item_lelang', models.IntegerField(null=True)),
                ('valid', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cca.round_cca')),
            ],
        ),
    ]
