# Generated by Django 4.2.2 on 2023-08-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0005_alter_hasil_cca_jenis_alter_round_cca_jenis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_detail_cca',
            name='max_blok',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round_detail_cca',
            name='spectrum_cap',
            field=models.IntegerField(null=True),
        ),
    ]
