# Generated by Django 4.2.2 on 2023-08-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0006_alter_round_detail_cca_max_blok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_detail_cca',
            name='parent',
        ),
    ]
