# Generated by Django 4.2.2 on 2023-09-08 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('adm_lelang', '0052_alter_detail_itemlelang_harga_minimal'),
        ('cca', '0007_remove_round_detail_cca_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_increase_cca',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cca_price_dibuat_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price_increase_cca',
            name='diubah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cca_price_diubah_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='price_increase_cca',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang'),
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='status_round',
            field=models.CharField(choices=[('STA', 'START'), ('STO', 'STOP'), ('SUS', 'SUSPEND'), ('CLO', 'CLOSED'), ('FIN', 'FINAL'), ('INI', 'INIT'), ('NON', 'NONE'), ('WAI', 'WAIT')], default='NON', max_length=3),
        ),
        migrations.CreateModel(
            name='round_cca2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.JSONField(null=True)),
                ('prev_price', models.JSONField(null=True)),
                ('activity', models.IntegerField(null=True)),
                ('corrected', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='round_cca_dibuat_oleh', to='userman.bidder')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='round_cca_dibuat_oleh', to='adm_lelang.item_lelang')),
            ],
        ),
        migrations.CreateModel(
            name='obyek_seleksi_cca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=25, verbose_name='Alamat IP')),
                ('eli_awal', models.IntegerField(blank=True, verbose_name='Blok Awal')),
                ('is_block_ip', models.BooleanField(default=False, verbose_name='IP Diblok?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bidder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user', verbose_name='Bidder')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cca_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cca_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang', verbose_name='Obyek Seleksi')),
            ],
        ),
    ]
