# Generated by Django 4.2.2 on 2023-09-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('cca', '0008_price_increase_cca_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasil_cca',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user'),
        ),
        migrations.AlterField(
            model_name='obyek_seleksi_cca',
            name='eli_awal',
            field=models.IntegerField(blank=True, verbose_name='Eligibility Awal'),
        ),
        migrations.AlterField(
            model_name='round_cca',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user'),
        ),
        migrations.AlterField(
            model_name='round_cca2',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='round_cca_dibuat_oleh', to='userman.bidder_user'),
        ),
        migrations.DeleteModel(
            name='price_increase_cca',
        ),
    ]
