# Generated by Django 4.2.2 on 2023-09-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0067_alter_admin_jabatan_alter_bidder_list_jabatan_and_more'),
        ('cca', '0009_alter_hasil_cca_bidder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sum_round_cca',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('status_round', models.CharField(choices=[('STA', 'START'), ('STO', 'STOP'), ('SUS', 'SUSPEND'), ('CLO', 'CLOSED'), ('FIN', 'FINAL'), ('INI', 'INIT'), ('NON', 'NONE'), ('WAI', 'WAIT')], max_length=3)),
                ('count', models.IntegerField()),
                ('mulai', models.CharField(max_length=25)),
                ('selesai', models.CharField(max_length=25)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='round_detail_cca',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_user'),
        ),
    ]
