# Generated by Django 4.2.2 on 2023-09-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0053_alter_pengumuman_tgl_release_alter_undangan_judul_and_more'),
        ('cca', '0010_sum_round_cca_alter_round_detail_cca_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_cca',
            name='block',
        ),
        migrations.RemoveField(
            model_name='round_cca',
            name='price',
        ),
        migrations.RemoveField(
            model_name='round_detail_cca',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='round_detail_cca',
            name='item_lelang',
        ),
        migrations.AddField(
            model_name='round_detail_cca',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cca.round_cca'),
        ),
        migrations.AlterField(
            model_name='round_detail_cca',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang'),
        ),
    ]
