# Generated by Django 4.2.2 on 2023-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0011_remove_round_cca_block_remove_round_cca_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_detail_cca',
            name='harga_minimal',
            field=models.FloatField(null=True),
        ),
    ]
