# Generated by Django 4.2.2 on 2023-09-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0053_alter_pengumuman_tgl_release_alter_undangan_judul_and_more'),
        ('cca', '0012_round_detail_cca_harga_minimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasil_cca',
            name='block',
        ),
        migrations.RemoveField(
            model_name='hasil_cca',
            name='item',
        ),
        migrations.RemoveField(
            model_name='hasil_cca',
            name='penawaran',
        ),
        migrations.RemoveField(
            model_name='hasil_cca',
            name='price',
        ),
        migrations.CreateModel(
            name='hasil_detail_cca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('block', models.IntegerField()),
                ('submit', models.DateTimeField(editable=False, null=True)),
                ('berlaku', models.BooleanField(default=False, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cca.hasil_cca')),
            ],
        ),
        migrations.CreateModel(
            name='hasil2_detail_cca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('ranking_putaran', models.IntegerField(blank=True, null=True)),
                ('berlaku', models.BooleanField(default=False, null=True)),
                ('submit', models.DateTimeField(editable=False, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cca.hasil_cca')),
            ],
        ),
    ]
