# Generated by Django 4.2.5 on 2023-10-05 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_lelang', '0054_alter_pengumuman_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cca', '0013_remove_hasil_cca_block_remove_hasil_cca_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='matrix_hasil_cr',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('json_agg', models.JSONField()),
                ('kombinasi', models.JSONField()),
                ('total', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cca_price_increase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentang_min', models.IntegerField(null=True, verbose_name='Rentang Bawah')),
                ('rentang_max', models.IntegerField(null=True, verbose_name='Rentang Atas')),
                ('kenaikan', models.FloatField(verbose_name='Kenaikan (%)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pertama')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Diubah Terakhir')),
                ('detail_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.detail_itemlelang')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cca_price_increase_dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cca_price_increase_diubah_oleh', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm_lelang.item_lelang')),
            ],
        ),
    ]
