# Generated by Django 4.2.5 on 2023-10-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0068_users_dibuat_oleh_users_diubah_oleh_users_pending'),
        ('cca', '0014_matrix_hasil_cr_cca_price_increase'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil_cca',
            name='berita_acara_unsigned',
            field=models.FileField(blank=True, upload_to='upload/bidder'),
        ),
        migrations.AddField(
            model_name='hasil_cca',
            name='perwakilan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userman.bidder_perwakilan'),
        ),
    ]
