# Generated by Django 4.2.5 on 2023-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0015_hasil_cca_berita_acara_unsigned_hasil_cca_perwakilan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasil_detail_cca',
            name='berlaku',
        ),
        migrations.AddField(
            model_name='hasil_cca',
            name='activity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hasil_cca',
            name='revelaled',
            field=models.BooleanField(default=False),
        ),
    ]
