# Generated by Django 4.2.5 on 2023-10-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0016_remove_hasil_detail_cca_berlaku_hasil_cca_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil_cca',
            name='eli',
            field=models.IntegerField(default=0),
        ),
    ]
