# Generated by Django 4.2.2 on 2023-10-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0017_hasil_cca_eli'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasil_auctioner_maxmin_cca',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(verbose_name='Putaran')),
                ('item_lelang', models.IntegerField()),
                ('block', models.IntegerField()),
                ('harga_max', models.FloatField()),
                ('harga_min', models.FloatField()),
                ('block_max', models.FloatField()),
                ('block_min', models.FloatField()),
                ('max_block', models.IntegerField()),
                ('harga_minimal', models.FloatField()),
                ('spectrum_cap', models.IntegerField()),
                ('persen1', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matrix2_cr',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('json_agg', models.JSONField()),
                ('kombinasi', models.JSONField()),
                ('total', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='hasil_highest_cca',
        ),
        migrations.AddField(
            model_name='hasil_cca',
            name='mulai',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hasil_cca',
            name='selesai',
            field=models.DateTimeField(null=True),
        ),
    ]
